"""
California municipalities — city hall / city clerk addresses for service of process.
Used by the small claims autofiller to populate the defendant section.
"""

# Each entry: name, hall_address, city, zip, clerk_title
# agent_* fields mirror the hall address (City Clerk is the agent for service on cities)
_CITIES_RAW = [
    ("Adelanto",          "Town of Adelanto",       "11600 Air Expressway",           "Adelanto",          "92301", "City Clerk"),
    ("Agoura Hills",      "City of Agoura Hills",   "30001 Ladyface Ct",              "Agoura Hills",      "91301", "City Clerk"),
    ("Alameda",           "City of Alameda",        "2263 Santa Clara Avenue",        "Alameda",           "94501", "City Clerk"),
    ("Albany",            "City of Albany",         "1000 San Pablo Ave",             "Albany",            "94706", "City Clerk"),
    ("Alhambra",          "City of Alhambra",       "111 S First St",                 "Alhambra",          "91801", "City Clerk"),
    ("Aliso Viejo",       "City of Aliso Viejo",    "12 Journey",                     "Aliso Viejo",       "92656", "City Clerk"),
    ("Alturas",           "City of Alturas",        "200 W North St",                 "Alturas",           "96101", "City Clerk"),
    ("American Canyon",   "City of American Canyon","4831 Broadway",                  "American Canyon",   "94503", "City Clerk"),
    ("Anaheim",           "City of Anaheim",        "200 S Anaheim Blvd",             "Anaheim",           "92805", "City Clerk"),
    ("Anderson",          "City of Anderson",       "1887 Howard St",                 "Anderson",          "96007", "City Clerk"),
    ("Angels Camp",       "City of Angels Camp",    "584 S Main St",                  "Angels Camp",       "95222", "City Clerk"),
    ("Antioch",           "City of Antioch",        "200 H St",                       "Antioch",           "94509", "City Clerk"),
    ("Apple Valley",      "Town of Apple Valley",   "14955 Dale Evans Pkwy",          "Apple Valley",      "92307", "Town Clerk"),
    ("Arcadia",           "City of Arcadia",        "240 W Huntington Dr",            "Arcadia",           "91007", "City Clerk"),
    ("Arcata",            "City of Arcata",         "736 F St",                       "Arcata",            "95521", "City Clerk"),
    ("Arroyo Grande",     "City of Arroyo Grande",  "300 E Branch St",                "Arroyo Grande",     "93420", "City Clerk"),
    ("Artesia",           "City of Artesia",        "18747 Clarkdale Ave",            "Artesia",           "90701", "City Clerk"),
    ("Arvin",             "City of Arvin",          "200 Campus Dr",                  "Arvin",             "93203", "City Clerk"),
    ("Atascadero",        "City of Atascadero",     "6500 Palma Ave",                 "Atascadero",        "93422", "City Clerk"),
    ("Atherton",          "Town of Atherton",       "91 Ashfield Rd",                 "Atherton",          "94027", "Town Clerk"),
    ("Atwater",           "City of Atwater",        "750 Bellevue Rd",                "Atwater",           "95301", "City Clerk"),
    ("Auburn",            "City of Auburn",         "1225 Lincoln Way",               "Auburn",            "95603", "City Clerk"),
    ("Avalon",            "City of Avalon",         "410 Avalon Canyon Rd",           "Avalon",            "90704", "City Clerk"),
    ("Avenal",            "City of Avenal",         "919 Skyline Blvd",               "Avenal",            "93204", "City Clerk"),
    ("Azusa",             "City of Azusa",          "213 E Foothill Blvd",            "Azusa",             "91702", "City Clerk"),
    ("Bakersfield",       "City of Bakersfield",    "1501 Truxtun Ave",               "Bakersfield",       "93301", "City Clerk"),
    ("Baldwin Park",      "City of Baldwin Park",   "14403 E Pacific Ave",            "Baldwin Park",      "91706", "City Clerk"),
    ("Banning",           "City of Banning",        "99 E Ramsey St",                 "Banning",           "92220", "City Clerk"),
    ("Barstow",           "City of Barstow",        "220 E Mountain View St",         "Barstow",           "92311", "City Clerk"),
    ("Bay Point",         "City of Bay Point",      "1 Civic Dr",                     "Pittsburg",         "94565", "City Clerk"),
    ("Beaumont",          "City of Beaumont",       "550 E Sixth St",                 "Beaumont",          "92223", "City Clerk"),
    ("Bell",              "City of Bell",           "6330 Pine Ave",                  "Bell",              "90201", "City Clerk"),
    ("Bell Gardens",      "City of Bell Gardens",   "7100 Garfield Ave",              "Bell Gardens",      "90201", "City Clerk"),
    ("Bellflower",        "City of Bellflower",     "16600 Civic Center Dr",          "Bellflower",        "90706", "City Clerk"),
    ("Belmont",           "City of Belmont",        "1 Twin Pines Ln",                "Belmont",           "94002", "City Clerk"),
    ("Belvedere",         "City of Belvedere",      "450 San Rafael Ave",             "Belvedere",         "94920", "City Clerk"),
    ("Benicia",           "City of Benicia",        "250 E L St",                     "Benicia",           "94510", "City Clerk"),
    ("Berkeley",          "City of Berkeley",       "2180 Milvia St",                 "Berkeley",          "94704", "City Clerk"),
    ("Beverly Hills",     "City of Beverly Hills",  "455 N Rexford Dr",               "Beverly Hills",     "90210", "City Clerk"),
    ("Big Bear Lake",     "City of Big Bear Lake",  "39707 Big Bear Blvd",            "Big Bear Lake",     "92315", "City Clerk"),
    ("Biggs",             "City of Biggs",          "465 B St",                       "Biggs",             "95917", "City Clerk"),
    ("Bishop",            "City of Bishop",         "377 W Line St",                  "Bishop",            "93514", "City Clerk"),
    ("Blue Lake",         "City of Blue Lake",      "111 Greenwood Ave",              "Blue Lake",         "95525", "City Clerk"),
    ("Blythe",            "City of Blythe",         "235 N Broadway",                 "Blythe",            "92225", "City Clerk"),
    ("Bradbury",          "City of Bradbury",       "600 Winston Ave",                "Bradbury",          "91008", "City Clerk"),
    ("Brawley",           "City of Brawley",        "383 Main St",                    "Brawley",           "92227", "City Clerk"),
    ("Brea",              "City of Brea",           "1 Civic Center Cir",             "Brea",              "92821", "City Clerk"),
    ("Brentwood",         "City of Brentwood",      "708 Third St",                   "Brentwood",         "94513", "City Clerk"),
    ("Brisbane",          "City of Brisbane",       "50 Park Place",                  "Brisbane",          "94005", "City Clerk"),
    ("Buena Park",        "City of Buena Park",     "6650 Beach Blvd",                "Buena Park",        "90621", "City Clerk"),
    ("Burbank",           "City of Burbank",        "275 E Olive Ave",                "Burbank",           "91502", "City Clerk"),
    ("Burlingame",        "City of Burlingame",     "501 Primrose Rd",                "Burlingame",        "94010", "City Clerk"),
    ("Calexico",          "City of Calexico",       "608 Heber Ave",                  "Calexico",          "92231", "City Clerk"),
    ("Calimesa",          "City of Calimesa",       "908 Park Ave",                   "Calimesa",          "92320", "City Clerk"),
    ("Calipatria",        "City of Calipatria",     "125 N Park Ave",                 "Calipatria",        "92233", "City Clerk"),
    ("Calistoga",         "City of Calistoga",      "1232 Washington St",             "Calistoga",         "94515", "City Clerk"),
    ("Camarillo",         "City of Camarillo",      "601 Carmen Dr",                  "Camarillo",         "93010", "City Clerk"),
    ("Campbell",          "City of Campbell",       "70 N First St",                  "Campbell",          "95008", "City Clerk"),
    ("Canyon Lake",       "City of Canyon Lake",    "31516 Railroad Canyon Rd",       "Canyon Lake",       "92587", "City Clerk"),
    ("Capitola",          "City of Capitola",       "420 Capitola Ave",               "Capitola",          "95010", "City Clerk"),
    ("Carlsbad",          "City of Carlsbad",       "1200 Carlsbad Village Dr",       "Carlsbad",          "92008", "City Clerk"),
    ("Carmel-by-the-Sea", "City of Carmel-by-the-Sea","Monte Verde St & Ocean Ave",  "Carmel-by-the-Sea", "93921", "City Clerk"),
    ("Carson",            "City of Carson",         "701 E Carson St",                "Carson",            "90745", "City Clerk"),
    ("Cathedral City",    "City of Cathedral City", "68700 Avenida Lalo Guerrero",    "Cathedral City",    "92234", "City Clerk"),
    ("Ceres",             "City of Ceres",          "2720 Second St",                 "Ceres",             "95307", "City Clerk"),
    ("Cerritos",          "City of Cerritos",       "18125 Bloomfield Ave",           "Cerritos",          "90703", "City Clerk"),
    ("Chico",             "City of Chico",          "411 Main St",                    "Chico",             "95928", "City Clerk"),
    ("Chino",             "City of Chino",          "13220 Central Ave",              "Chino",             "91710", "City Clerk"),
    ("Chino Hills",       "City of Chino Hills",    "14000 City Center Dr",           "Chino Hills",       "91709", "City Clerk"),
    ("Chula Vista",       "City of Chula Vista",    "276 Fourth Ave",                 "Chula Vista",       "91910", "City Clerk"),
    ("Citrus Heights",    "City of Citrus Heights", "6237 Fountain Square Dr",        "Citrus Heights",    "95621", "City Clerk"),
    ("Claremont",         "City of Claremont",      "207 Harvard Ave",                "Claremont",         "91711", "City Clerk"),
    ("Clayton",           "City of Clayton",        "6000 Heritage Trail",            "Clayton",           "94517", "City Clerk"),
    ("Clearlake",         "City of Clearlake",      "14050 Olympic Dr",               "Clearlake",         "95422", "City Clerk"),
    ("Cloverdale",        "City of Cloverdale",     "124 N Cloverdale Blvd",          "Cloverdale",        "95425", "City Clerk"),
    ("Clovis",            "City of Clovis",         "1033 Fifth St",                  "Clovis",            "93612", "City Clerk"),
    ("Coachella",         "City of Coachella",      "1515 Sixth St",                  "Coachella",         "92236", "City Clerk"),
    ("Coalinga",          "City of Coalinga",       "155 W Durian Ave",               "Coalinga",          "93210", "City Clerk"),
    ("Colfax",            "City of Colfax",         "33 Railroad St",                 "Colfax",            "95713", "City Clerk"),
    ("Colton",            "City of Colton",         "650 N La Cadena Dr",             "Colton",            "92324", "City Clerk"),
    ("Colusa",            "City of Colusa",         "425 Webster St",                 "Colusa",            "95932", "City Clerk"),
    ("Commerce",          "City of Commerce",       "2535 Commerce Way",              "Commerce",          "90040", "City Clerk"),
    ("Compton",           "City of Compton",        "205 S Willowbrook Ave",          "Compton",           "90220", "City Clerk"),
    ("Concord",           "City of Concord",        "1950 Parkside Dr",               "Concord",           "94519", "City Clerk"),
    ("Corcoran",          "City of Corcoran",       "832 Whitley Ave",                "Corcoran",          "93212", "City Clerk"),
    ("Corning",           "City of Corning",        "794 Third St",                   "Corning",           "96021", "City Clerk"),
    ("Corona",            "City of Corona",         "400 S Vicentia Ave",             "Corona",            "92882", "City Clerk"),
    ("Coronado",          "City of Coronado",       "1825 Strand Way",                "Coronado",          "92118", "City Clerk"),
    ("Costa Mesa",        "City of Costa Mesa",     "77 Fair Dr",                     "Costa Mesa",        "92626", "City Clerk"),
    ("Cotati",            "City of Cotati",         "201 W Sierra Ave",               "Cotati",            "94931", "City Clerk"),
    ("Covina",            "City of Covina",         "125 E College St",               "Covina",            "91723", "City Clerk"),
    ("Crescent City",     "City of Crescent City",  "377 J St",                       "Crescent City",     "95531", "City Clerk"),
    ("Cudahy",            "City of Cudahy",         "5220 Santa Ana St",              "Cudahy",            "90201", "City Clerk"),
    ("Culver City",       "City of Culver City",    "9770 Culver Blvd",               "Culver City",       "90232", "City Clerk"),
    ("Cupertino",         "City of Cupertino",      "10300 Torre Ave",                "Cupertino",         "95014", "City Clerk"),
    ("Cypress",           "City of Cypress",        "5275 Orange Ave",                "Cypress",           "90630", "City Clerk"),
    ("Daly City",         "City of Daly City",      "333 90th St",                    "Daly City",         "94015", "City Clerk"),
    ("Dana Point",        "City of Dana Point",     "33282 Golden Lantern",           "Dana Point",        "92629", "City Clerk"),
    ("Danville",          "Town of Danville",       "510 La Gonda Way",               "Danville",          "94526", "Town Clerk"),
    ("Davis",             "City of Davis",          "23 Russell Blvd",                "Davis",             "95616", "City Clerk"),
    ("Del Mar",           "City of Del Mar",        "1050 Camino Del Mar",            "Del Mar",           "92014", "City Clerk"),
    ("Desert Hot Springs","City of Desert Hot Springs","65950 Pierson Blvd",          "Desert Hot Springs","92240", "City Clerk"),
    ("Diamond Bar",       "City of Diamond Bar",    "21810 Copley Dr",                "Diamond Bar",       "91765", "City Clerk"),
    ("Dinuba",            "City of Dinuba",         "405 E El Monte Way",             "Dinuba",            "93618", "City Clerk"),
    ("Dixon",             "City of Dixon",          "600 E A St",                     "Dixon",             "95620", "City Clerk"),
    ("Downey",            "City of Downey",         "11111 Brookshire Ave",           "Downey",            "90241", "City Clerk"),
    ("Duarte",            "City of Duarte",         "1600 Huntington Dr",             "Duarte",            "91010", "City Clerk"),
    ("Dublin",            "City of Dublin",         "100 Civic Plaza",                "Dublin",            "94568", "City Clerk"),
    ("Dunsmuir",          "City of Dunsmuir",       "5915 Dunsmuir Ave",              "Dunsmuir",          "96025", "City Clerk"),
    ("East Palo Alto",    "City of East Palo Alto", "2415 University Ave",            "East Palo Alto",    "94303", "City Clerk"),
    ("El Cajon",          "City of El Cajon",       "200 E Main St",                  "El Cajon",          "92020", "City Clerk"),
    ("El Centro",         "City of El Centro",      "1275 Main St",                   "El Centro",         "92243", "City Clerk"),
    ("El Cerrito",        "City of El Cerrito",     "10890 San Pablo Ave",            "El Cerrito",        "94530", "City Clerk"),
    ("El Monte",          "City of El Monte",       "11333 Valley Blvd",              "El Monte",          "91731", "City Clerk"),
    ("El Segundo",        "City of El Segundo",     "350 Main St",                    "El Segundo",        "90245", "City Clerk"),
    ("Elk Grove",         "City of Elk Grove",      "8380 Laguna Palms Way",          "Elk Grove",         "95758", "City Clerk"),
    ("Emeryville",        "City of Emeryville",     "1333 Park Ave",                  "Emeryville",        "94608", "City Clerk"),
    ("Escalon",           "City of Escalon",        "838 Main St",                    "Escalon",           "95320", "City Clerk"),
    ("Escondido",         "City of Escondido",      "201 N Broadway",                 "Escondido",         "92025", "City Clerk"),
    ("Etna",              "City of Etna",           "500 Main St",                    "Etna",              "96027", "City Clerk"),
    ("Eureka",            "City of Eureka",         "531 K St",                       "Eureka",            "95501", "City Clerk"),
    ("Exeter",            "City of Exeter",         "137 N F St",                     "Exeter",            "93221", "City Clerk"),
    ("Fairfax",           "Town of Fairfax",        "142 Bolinas Rd",                 "Fairfax",           "94930", "Town Clerk"),
    ("Fairfield",         "City of Fairfield",      "1000 Webster St",                "Fairfield",         "94533", "City Clerk"),
    ("Farmersville",      "City of Farmersville",   "909 W Visalia Rd",               "Farmersville",      "93223", "City Clerk"),
    ("Ferndale",          "City of Ferndale",       "834 Main St",                    "Ferndale",          "95536", "City Clerk"),
    ("Fillmore",          "City of Fillmore",       "250 Central Ave",                "Fillmore",          "93015", "City Clerk"),
    ("Firebaugh",         "City of Firebaugh",      "1133 P St",                      "Firebaugh",         "93622", "City Clerk"),
    ("Folsom",            "City of Folsom",         "50 Natoma St",                   "Folsom",            "95630", "City Clerk"),
    ("Fontana",           "City of Fontana",        "8353 Sierra Ave",                "Fontana",           "92335", "City Clerk"),
    ("Fort Bragg",        "City of Fort Bragg",     "416 N Franklin St",              "Fort Bragg",        "95437", "City Clerk"),
    ("Fort Jones",        "City of Fort Jones",     "11930 N Main St",                "Fort Jones",        "96032", "City Clerk"),
    ("Fortuna",           "City of Fortuna",        "621 11th St",                    "Fortuna",           "95540", "City Clerk"),
    ("Foster City",       "City of Foster City",    "610 Foster City Blvd",           "Foster City",       "94404", "City Clerk"),
    ("Fountain Valley",   "City of Fountain Valley","10200 Slater Ave",               "Fountain Valley",   "92708", "City Clerk"),
    ("Fowler",            "City of Fowler",         "128 E Merced St",                "Fowler",            "93625", "City Clerk"),
    ("Fremont",           "City of Fremont",        "3300 Capitol Ave",               "Fremont",           "94538", "City Clerk"),
    ("Fresno",            "City of Fresno",         "2600 Fresno St",                 "Fresno",            "93721", "City Clerk"),
    ("Fullerton",         "City of Fullerton",      "303 W Commonwealth Ave",         "Fullerton",         "92832", "City Clerk"),
    ("Galt",              "City of Galt",           "380 Civic Dr",                   "Galt",              "95632", "City Clerk"),
    ("Garden Grove",      "City of Garden Grove",   "11222 Acacia Pkwy",              "Garden Grove",      "92840", "City Clerk"),
    ("Gardena",           "City of Gardena",        "1700 W 162nd St",                "Gardena",           "90247", "City Clerk"),
    ("Gilroy",            "City of Gilroy",         "7351 Rosanna St",                "Gilroy",            "95020", "City Clerk"),
    ("Glendale",          "City of Glendale",       "613 E Broadway",                 "Glendale",          "91206", "City Clerk"),
    ("Glendora",          "City of Glendora",       "116 E Foothill Blvd",            "Glendora",          "91741", "City Clerk"),
    ("Gonzales",          "City of Gonzales",       "147 Fourth St",                  "Gonzales",          "93926", "City Clerk"),
    ("Grand Terrace",     "City of Grand Terrace",  "22795 Barton Rd",                "Grand Terrace",     "92313", "City Clerk"),
    ("Grass Valley",      "City of Grass Valley",   "125 E Main St",                  "Grass Valley",      "95945", "City Clerk"),
    ("Greenfield",        "City of Greenfield",     "599 El Camino Real",             "Greenfield",        "93927", "City Clerk"),
    ("Gridley",           "City of Gridley",        "685 Kentucky St",                "Gridley",           "95948", "City Clerk"),
    ("Grover Beach",      "City of Grover Beach",   "154 S Eighth St",                "Grover Beach",      "93433", "City Clerk"),
    ("Guadalupe",         "City of Guadalupe",      "918 Obispo St",                  "Guadalupe",         "93434", "City Clerk"),
    ("Gustine",           "City of Gustine",        "358 Fifth St",                   "Gustine",           "95322", "City Clerk"),
    ("Half Moon Bay",     "City of Half Moon Bay",  "501 Main St",                    "Half Moon Bay",     "94019", "City Clerk"),
    ("Hanford",           "City of Hanford",        "317 N Douty St",                 "Hanford",           "93230", "City Clerk"),
    ("Hawaiian Gardens",  "City of Hawaiian Gardens","21815 Pioneer Blvd",            "Hawaiian Gardens",  "90716", "City Clerk"),
    ("Hawthorne",         "City of Hawthorne",      "4455 W 126th St",                "Hawthorne",         "90250", "City Clerk"),
    ("Hayward",           "City of Hayward",        "777 B St",                       "Hayward",           "94541", "City Clerk"),
    ("Healdsburg",        "City of Healdsburg",     "401 Grove St",                   "Healdsburg",        "95448", "City Clerk"),
    ("Hemet",             "City of Hemet",          "445 E Florida Ave",              "Hemet",             "92543", "City Clerk"),
    ("Hercules",          "City of Hercules",       "111 Civic Dr",                   "Hercules",          "94547", "City Clerk"),
    ("Hermosa Beach",     "City of Hermosa Beach",  "1315 Valley Dr",                 "Hermosa Beach",     "90254", "City Clerk"),
    ("Hesperia",          "City of Hesperia",       "9700 Seventh Ave",               "Hesperia",          "92345", "City Clerk"),
    ("Highland",          "City of Highland",       "27215 Base Line",                "Highland",          "92346", "City Clerk"),
    ("Hillsborough",      "Town of Hillsborough",   "1600 Floribunda Ave",            "Hillsborough",      "94010", "Town Clerk"),
    ("Hollister",         "City of Hollister",      "375 Fifth St",                   "Hollister",         "95023", "City Clerk"),
    ("Holtville",         "City of Holtville",      "121 W Fifth St",                 "Holtville",         "92250", "City Clerk"),
    ("Huntington Beach",  "City of Huntington Beach","2000 Main St",                  "Huntington Beach",  "92648", "City Clerk"),
    ("Huntington Park",   "City of Huntington Park","6550 Miles Ave",                 "Huntington Park",   "90255", "City Clerk"),
    ("Imperial",          "City of Imperial",       "420 S Imperial Ave",             "Imperial",          "92251", "City Clerk"),
    ("Imperial Beach",    "City of Imperial Beach", "825 Imperial Beach Blvd",        "Imperial Beach",    "91932", "City Clerk"),
    ("Indian Wells",      "City of Indian Wells",   "44950 Eldorado Dr",              "Indian Wells",      "92210", "City Clerk"),
    ("Indio",             "City of Indio",          "100 Civic Center Mall",          "Indio",             "92201", "City Clerk"),
    ("Industry",          "City of Industry",       "15625 E Industry Hills Pkwy",    "City of Industry",  "91744", "City Clerk"),
    ("Inglewood",         "City of Inglewood",      "One Manchester Blvd",            "Inglewood",         "90301", "City Clerk"),
    ("Ione",              "City of Ione",           "1 E Main St",                    "Ione",              "95640", "City Clerk"),
    ("Irvine",            "City of Irvine",         "One Civic Center Plaza",         "Irvine",            "92606", "City Clerk"),
    ("Irwindale",         "City of Irwindale",      "5050 N Irwindale Ave",           "Irwindale",         "91702", "City Clerk"),
    ("Isleton",           "City of Isleton",        "100 Second St",                  "Isleton",           "95641", "City Clerk"),
    ("Jackson",           "City of Jackson",        "33 Broadway",                    "Jackson",           "95642", "City Clerk"),
    ("Jurupa Valley",     "City of Jurupa Valley",  "8930 Limonite Ave",              "Jurupa Valley",     "91752", "City Clerk"),
    ("Kerman",            "City of Kerman",         "850 S Madera Ave",               "Kerman",            "93630", "City Clerk"),
    ("King City",         "City of King City",      "212 S Vanderhurst Ave",          "King City",         "93930", "City Clerk"),
    ("Kingsburg",         "City of Kingsburg",      "1401 Draper St",                 "Kingsburg",         "93631", "City Clerk"),
    ("La Canada Flintridge","City of La Canada Flintridge","1327 Foothill Blvd",      "La Canada Flintridge","91011","City Clerk"),
    ("La Habra",          "City of La Habra",       "201 E La Habra Blvd",            "La Habra",          "90631", "City Clerk"),
    ("La Habra Heights",  "City of La Habra Heights","1245 N Hacienda Rd",            "La Habra Heights",  "90631", "City Clerk"),
    ("La Mesa",           "City of La Mesa",        "8130 Allison Ave",               "La Mesa",           "91942", "City Clerk"),
    ("La Mirada",         "City of La Mirada",      "13700 La Mirada Blvd",           "La Mirada",         "90638", "City Clerk"),
    ("La Palma",          "City of La Palma",       "7822 Walker St",                 "La Palma",          "90623", "City Clerk"),
    ("La Puente",         "City of La Puente",      "15900 E Main St",                "La Puente",         "91744", "City Clerk"),
    ("La Quinta",         "City of La Quinta",      "78495 Calle Tampico",            "La Quinta",         "92253", "City Clerk"),
    ("La Verne",          "City of La Verne",       "3660 D St",                      "La Verne",          "91750", "City Clerk"),
    ("Lafayette",         "City of Lafayette",      "3675 Mount Diablo Blvd",         "Lafayette",         "94549", "City Clerk"),
    ("Laguna Beach",      "City of Laguna Beach",   "505 Forest Ave",                 "Laguna Beach",      "92651", "City Clerk"),
    ("Laguna Hills",      "City of Laguna Hills",   "24035 El Toro Rd",               "Laguna Hills",      "92653", "City Clerk"),
    ("Laguna Niguel",     "City of Laguna Niguel",  "30111 Crown Valley Pkwy",        "Laguna Niguel",     "92677", "City Clerk"),
    ("Laguna Woods",      "City of Laguna Woods",   "24264 El Toro Rd",               "Laguna Woods",      "92637", "City Clerk"),
    ("Lake Elsinore",     "City of Lake Elsinore",  "130 S Main St",                  "Lake Elsinore",     "92530", "City Clerk"),
    ("Lake Forest",       "City of Lake Forest",    "100 Civic Center Dr",            "Lake Forest",       "92630", "City Clerk"),
    ("Lakeport",          "City of Lakeport",       "225 Park St",                    "Lakeport",          "95453", "City Clerk"),
    ("Lakewood",          "City of Lakewood",       "5050 N Clark Ave",               "Lakewood",          "90712", "City Clerk"),
    ("Lancaster",         "City of Lancaster",      "44933 Fern Ave",                 "Lancaster",         "93534", "City Clerk"),
    ("Larkspur",          "City of Larkspur",       "400 Magnolia Ave",               "Larkspur",          "94939", "City Clerk"),
    ("Lathrop",           "City of Lathrop",        "390 Towne Centre Dr",            "Lathrop",           "95330", "City Clerk"),
    ("Lawndale",          "City of Lawndale",       "14717 Burin Ave",                "Lawndale",          "90260", "City Clerk"),
    ("Lemon Grove",       "City of Lemon Grove",    "3232 Main St",                   "Lemon Grove",       "91945", "City Clerk"),
    ("Lemoore",           "City of Lemoore",        "711 W Cinnamon Dr",              "Lemoore",           "93245", "City Clerk"),
    ("Lincoln",           "City of Lincoln",        "600 Sixth St",                   "Lincoln",           "95648", "City Clerk"),
    ("Lindsay",           "City of Lindsay",        "251 E Honolulu St",              "Lindsay",           "93247", "City Clerk"),
    ("Live Oak",          "City of Live Oak",       "9955 Live Oak Blvd",             "Live Oak",          "95953", "City Clerk"),
    ("Livermore",         "City of Livermore",      "1052 S Livermore Ave",           "Livermore",         "94550", "City Clerk"),
    ("Livingston",        "City of Livingston",     "1416 C St",                      "Livingston",        "95334", "City Clerk"),
    ("Lodi",              "City of Lodi",           "221 W Pine St",                  "Lodi",              "95240", "City Clerk"),
    ("Loma Linda",        "City of Loma Linda",     "25541 Barton Rd",                "Loma Linda",        "92354", "City Clerk"),
    ("Lomita",            "City of Lomita",         "24300 Narbonne Ave",             "Lomita",            "90717", "City Clerk"),
    ("Lompoc",            "City of Lompoc",         "100 Civic Center Plaza",         "Lompoc",            "93436", "City Clerk"),
    ("Long Beach",        "City of Long Beach",     "411 W Ocean Blvd",               "Long Beach",        "90802", "City Clerk"),
    ("Los Alamitos",      "City of Los Alamitos",   "3191 Katella Ave",               "Los Alamitos",      "90720", "City Clerk"),
    ("Los Altos",         "City of Los Altos",      "1 N San Antonio Rd",             "Los Altos",         "94022", "City Clerk"),
    ("Los Altos Hills",   "Town of Los Altos Hills","26379 Fremont Rd",               "Los Altos Hills",   "94022", "Town Clerk"),
    ("Los Angeles",       "City of Los Angeles",    "200 N Spring St",                "Los Angeles",       "90012", "City Clerk"),
    ("Los Banos",         "City of Los Banos",      "520 J St",                       "Los Banos",         "93635", "City Clerk"),
    ("Los Gatos",         "Town of Los Gatos",      "110 E Main St",                  "Los Gatos",         "95030", "Town Clerk"),
    ("Lynwood",           "City of Lynwood",        "11330 Bullis Rd",                "Lynwood",           "90262", "City Clerk"),
    ("Madera",            "City of Madera",         "205 W Fourth St",                "Madera",            "93638", "City Clerk"),
    ("Malibu",            "City of Malibu",         "23825 Stuart Ranch Rd",          "Malibu",            "90265", "City Clerk"),
    ("Mammoth Lakes",     "Town of Mammoth Lakes",  "437 Old Mammoth Rd",             "Mammoth Lakes",     "93546", "Town Clerk"),
    ("Manhattan Beach",   "City of Manhattan Beach","1400 Highland Ave",              "Manhattan Beach",   "90266", "City Clerk"),
    ("Manteca",           "City of Manteca",        "1001 W Center St",               "Manteca",           "95337", "City Clerk"),
    ("Maricopa",          "City of Maricopa",       "100 E Fifth St",                 "Maricopa",          "93252", "City Clerk"),
    ("Marina",            "City of Marina",         "211 Hillcrest Ave",              "Marina",            "93933", "City Clerk"),
    ("Martinez",          "City of Martinez",       "525 Henrietta St",               "Martinez",          "94553", "City Clerk"),
    ("Marysville",        "City of Marysville",     "526 C St",                       "Marysville",        "95901", "City Clerk"),
    ("Maywood",           "City of Maywood",        "4319 E Slauson Ave",             "Maywood",           "90270", "City Clerk"),
    ("McFarland",         "City of McFarland",      "401 W Kern Ave",                 "McFarland",         "93250", "City Clerk"),
    ("Mendota",           "City of Mendota",        "643 Quince St",                  "Mendota",           "93640", "City Clerk"),
    ("Menifee",           "City of Menifee",        "29714 Haun Rd",                  "Menifee",           "92586", "City Clerk"),
    ("Menlo Park",        "City of Menlo Park",     "701 Laurel St",                  "Menlo Park",        "94025", "City Clerk"),
    ("Merced",            "City of Merced",         "678 W 18th St",                  "Merced",            "95340", "City Clerk"),
    ("Millbrae",          "City of Millbrae",       "621 Magnolia Ave",               "Millbrae",          "94030", "City Clerk"),
    ("Mill Valley",       "City of Mill Valley",    "26 Corte Madera Ave",            "Mill Valley",       "94941", "City Clerk"),
    ("Milpitas",          "City of Milpitas",       "455 E Calaveras Blvd",           "Milpitas",          "95035", "City Clerk"),
    ("Mission Hills",     "City of Mission Hills",  "City Hall",                      "Mission Hills",     "91345", "City Clerk"),
    ("Mission Viejo",     "City of Mission Viejo",  "200 Civic Center",               "Mission Viejo",     "92691", "City Clerk"),
    ("Modesto",           "City of Modesto",        "1010 Tenth St",                  "Modesto",           "95354", "City Clerk"),
    ("Monrovia",          "City of Monrovia",       "415 S Ivy Ave",                  "Monrovia",          "91016", "City Clerk"),
    ("Montclair",         "City of Montclair",      "5111 Benito St",                 "Montclair",         "91763", "City Clerk"),
    ("Monte Sereno",      "City of Monte Sereno",   "18041 Saratoga-Los Gatos Rd",    "Monte Sereno",      "95030", "City Clerk"),
    ("Montebello",        "City of Montebello",     "1600 W Beverly Blvd",            "Montebello",        "90640", "City Clerk"),
    ("Monterey",          "City of Monterey",       "580 Pacific St",                 "Monterey",          "93940", "City Clerk"),
    ("Monterey Park",     "City of Monterey Park",  "320 W Newmark Ave",              "Monterey Park",     "91754", "City Clerk"),
    ("Moorpark",          "City of Moorpark",       "799 Moorpark Ave",               "Moorpark",          "93021", "City Clerk"),
    ("Moraga",            "Town of Moraga",         "329 Rheem Blvd",                 "Moraga",            "94556", "Town Clerk"),
    ("Moreno Valley",     "City of Moreno Valley",  "14177 Frederick St",             "Moreno Valley",     "92552", "City Clerk"),
    ("Morgan Hill",       "City of Morgan Hill",    "17575 Peak Ave",                 "Morgan Hill",       "95037", "City Clerk"),
    ("Morro Bay",         "City of Morro Bay",      "595 Harbor St",                  "Morro Bay",         "93442", "City Clerk"),
    ("Mount Shasta",      "City of Mount Shasta",   "305 N Mt Shasta Blvd",           "Mount Shasta",      "96067", "City Clerk"),
    ("Mountain View",     "City of Mountain View",  "500 Castro St",                  "Mountain View",     "94041", "City Clerk"),
    ("Murrieta",          "City of Murrieta",       "1 Town Square",                  "Murrieta",          "92562", "City Clerk"),
    ("Napa",              "City of Napa",           "955 School St",                  "Napa",              "94559", "City Clerk"),
    ("National City",     "City of National City",  "1243 National City Blvd",        "National City",     "91950", "City Clerk"),
    ("Needles",           "City of Needles",        "817 Third St",                   "Needles",           "92363", "City Clerk"),
    ("Newark",            "City of Newark",         "37101 Newark Blvd",              "Newark",            "94560", "City Clerk"),
    ("Newman",            "City of Newman",         "1162 Main St",                   "Newman",            "95360", "City Clerk"),
    ("Newport Beach",     "City of Newport Beach",  "100 Civic Center Dr",            "Newport Beach",     "92660", "City Clerk"),
    ("Norco",             "City of Norco",          "2820 Clark Ave",                 "Norco",             "92860", "City Clerk"),
    ("Norwalk",           "City of Norwalk",        "12700 Norwalk Blvd",             "Norwalk",           "90650", "City Clerk"),
    ("Novato",            "City of Novato",         "922 Machin Ave",                 "Novato",            "94945", "City Clerk"),
    ("Oakland",           "City of Oakland",        "One Frank H. Ogawa Plaza",       "Oakland",           "94612", "City Clerk"),
    ("Oakdale",           "City of Oakdale",        "280 N Third Ave",                "Oakdale",           "95361", "City Clerk"),
    ("Oakley",            "City of Oakley",         "3231 Main St",                   "Oakley",            "94561", "City Clerk"),
    ("Oceanside",         "City of Oceanside",      "300 N Coast Hwy",                "Oceanside",         "92054", "City Clerk"),
    ("Ojai",              "City of Ojai",           "401 S Ventura St",               "Ojai",              "93023", "City Clerk"),
    ("Ontario",           "City of Ontario",        "303 E B St",                     "Ontario",           "91762", "City Clerk"),
    ("Orange",            "City of Orange",         "300 E Chapman Ave",              "Orange",            "92866", "City Clerk"),
    ("Orange Cove",       "City of Orange Cove",    "633 Sixth St",                   "Orange Cove",       "93646", "City Clerk"),
    ("Orinda",            "City of Orinda",         "22 Orinda Way",                  "Orinda",            "94563", "City Clerk"),
    ("Orland",            "City of Orland",         "815 Fourth St",                  "Orland",            "95963", "City Clerk"),
    ("Oroville",          "City of Oroville",       "1735 Montgomery St",             "Oroville",          "95965", "City Clerk"),
    ("Oxnard",            "City of Oxnard",         "305 W Third St",                 "Oxnard",            "93030", "City Clerk"),
    ("Pacific Grove",     "City of Pacific Grove",  "300 Forest Ave",                 "Pacific Grove",     "93950", "City Clerk"),
    ("Pacifica",          "City of Pacifica",       "170 Santa Maria Ave",            "Pacifica",          "94044", "City Clerk"),
    ("Palm Desert",       "City of Palm Desert",    "73510 Fred Waring Dr",           "Palm Desert",       "92260", "City Clerk"),
    ("Palm Springs",      "City of Palm Springs",   "3200 E Tahquitz Canyon Way",     "Palm Springs",      "92262", "City Clerk"),
    ("Palmdale",          "City of Palmdale",       "38300 Sierra Hwy",               "Palmdale",          "93550", "City Clerk"),
    ("Palo Alto",         "City of Palo Alto",      "250 Hamilton Ave",               "Palo Alto",         "94301", "City Clerk"),
    ("Palos Verdes Estates","City of Palos Verdes Estates","340 Palos Verdes Dr W",   "Palos Verdes Estates","90274","City Clerk"),
    ("Paradise",          "Town of Paradise",       "5555 Skyway",                    "Paradise",          "95969", "Town Clerk"),
    ("Paramount",         "City of Paramount",      "16400 Colorado Ave",             "Paramount",         "90723", "City Clerk"),
    ("Parlier",           "City of Parlier",        "1100 E Parlier Ave",             "Parlier",           "93648", "City Clerk"),
    ("Pasadena",          "City of Pasadena",       "100 N Garfield Ave",             "Pasadena",          "91109", "City Clerk"),
    ("Patterson",         "City of Patterson",      "1 Plaza",                        "Patterson",         "95363", "City Clerk"),
    ("Perris",            "City of Perris",         "101 N D St",                     "Perris",            "92570", "City Clerk"),
    ("Petaluma",          "City of Petaluma",       "11 English St",                  "Petaluma",          "94952", "City Clerk"),
    ("Piedmont",          "City of Piedmont",       "120 Vista Ave",                  "Piedmont",          "94611", "City Clerk"),
    ("Pinole",            "City of Pinole",         "2131 Pear St",                   "Pinole",            "94564", "City Clerk"),
    ("Pismo Beach",       "City of Pismo Beach",    "760 Mattie Rd",                  "Pismo Beach",       "93449", "City Clerk"),
    ("Pittsburg",         "City of Pittsburg",      "65 Civic Ave",                   "Pittsburg",         "94565", "City Clerk"),
    ("Placentia",         "City of Placentia",      "401 E Chapman Ave",              "Placentia",         "92870", "City Clerk"),
    ("Placerville",       "City of Placerville",    "549 Main St",                    "Placerville",       "95667", "City Clerk"),
    ("Pleasant Hill",     "City of Pleasant Hill",  "100 Gregory Ln",                 "Pleasant Hill",     "94523", "City Clerk"),
    ("Pleasanton",        "City of Pleasanton",     "200 Old Bernal Ave",             "Pleasanton",        "94566", "City Clerk"),
    ("Plymouth",          "City of Plymouth",       "9426 Main St",                   "Plymouth",          "95669", "City Clerk"),
    ("Point Arena",       "City of Point Arena",    "451 School St",                  "Point Arena",       "95468", "City Clerk"),
    ("Pomona",            "City of Pomona",         "505 S Garey Ave",                "Pomona",            "91766", "City Clerk"),
    ("Port Hueneme",      "City of Port Hueneme",   "250 N Ventura Rd",               "Port Hueneme",      "93041", "City Clerk"),
    ("Porterville",       "City of Porterville",    "291 N Main St",                  "Porterville",       "93257", "City Clerk"),
    ("Portola",           "City of Portola",        "35 Third Ave",                   "Portola",           "96122", "City Clerk"),
    ("Portola Valley",    "Town of Portola Valley", "765 Portola Rd",                 "Portola Valley",    "94028", "Town Clerk"),
    ("Poway",             "City of Poway",          "13325 Civic Center Dr",          "Poway",             "92064", "City Clerk"),
    ("Rancho Cordova",    "City of Rancho Cordova", "2729 Prospect Park Dr",          "Rancho Cordova",    "95670", "City Clerk"),
    ("Rancho Cucamonga",  "City of Rancho Cucamonga","10500 Civic Center Dr",         "Rancho Cucamonga",  "91730", "City Clerk"),
    ("Rancho Mirage",     "City of Rancho Mirage",  "69825 Hwy 111",                  "Rancho Mirage",     "92270", "City Clerk"),
    ("Rancho Palos Verdes","City of Rancho Palos Verdes","30940 Hawthorne Blvd",      "Rancho Palos Verdes","90275","City Clerk"),
    ("Rancho Santa Margarita","City of Rancho Santa Margarita","30211 Avenida De Las Banderas","Rancho Santa Margarita","92688","City Clerk"),
    ("Red Bluff",         "City of Red Bluff",      "555 Washington St",              "Red Bluff",         "96080", "City Clerk"),
    ("Redding",           "City of Redding",        "777 Cypress Ave",                "Redding",           "96001", "City Clerk"),
    ("Redlands",          "City of Redlands",       "35 Cajon St",                    "Redlands",          "92373", "City Clerk"),
    ("Redondo Beach",     "City of Redondo Beach",  "415 Diamond St",                 "Redondo Beach",     "90277", "City Clerk"),
    ("Redwood City",      "City of Redwood City",   "1017 Middlefield Rd",            "Redwood City",      "94063", "City Clerk"),
    ("Reedley",           "City of Reedley",        "845 G St",                       "Reedley",           "93654", "City Clerk"),
    ("Rialto",            "City of Rialto",         "150 S Palm Ave",                 "Rialto",            "92376", "City Clerk"),
    ("Richmond",          "City of Richmond",       "450 Civic Center Plaza",         "Richmond",          "94804", "City Clerk"),
    ("Ridgecrest",        "City of Ridgecrest",     "100 W California Ave",           "Ridgecrest",        "93555", "City Clerk"),
    ("Rio Dell",          "City of Rio Dell",       "675 Wildwood Ave",               "Rio Dell",          "95562", "City Clerk"),
    ("Rio Vista",         "City of Rio Vista",      "One Main St",                    "Rio Vista",         "94571", "City Clerk"),
    ("Ripon",             "City of Ripon",          "259 N Wilma Ave",                "Ripon",             "95366", "City Clerk"),
    ("Riverbank",         "City of Riverbank",      "6707 Third St",                  "Riverbank",         "95367", "City Clerk"),
    ("Riverside",         "City of Riverside",      "3900 Main St",                   "Riverside",         "92522", "City Clerk"),
    ("Rocklin",           "City of Rocklin",        "3970 Rocklin Rd",                "Rocklin",           "95677", "City Clerk"),
    ("Rohnert Park",      "City of Rohnert Park",   "130 Avram Ave",                  "Rohnert Park",      "94928", "City Clerk"),
    ("Rolling Hills",     "City of Rolling Hills",  "2 Portuguese Bend Rd",           "Rolling Hills",     "90274", "City Clerk"),
    ("Rolling Hills Estates","City of Rolling Hills Estates","4045 Palos Verdes Dr N","Rolling Hills Estates","90274","City Clerk"),
    ("Rosemead",          "City of Rosemead",       "8838 E Valley Blvd",             "Rosemead",          "91770", "City Clerk"),
    ("Roseville",         "City of Roseville",      "311 Vernon St",                  "Roseville",         "95678", "City Clerk"),
    ("Sacramento",        "City of Sacramento",     "915 I St",                       "Sacramento",        "95814", "City Clerk"),
    ("Salinas",           "City of Salinas",        "200 Lincoln Ave",                "Salinas",           "93901", "City Clerk"),
    ("San Bernardino",    "City of San Bernardino", "201 N E St",                     "San Bernardino",    "92401", "City Clerk"),
    ("San Bruno",         "City of San Bruno",      "567 El Camino Real",             "San Bruno",         "94066", "City Clerk"),
    ("San Buenaventura",  "City of San Buenaventura","501 Poli St",                   "Ventura",           "93001", "City Clerk"),
    ("San Carlos",        "City of San Carlos",     "600 Elm St",                     "San Carlos",        "94070", "City Clerk"),
    ("San Clemente",      "City of San Clemente",   "910 Calle Negocio",              "San Clemente",      "92673", "City Clerk"),
    ("San Diego",         "City of San Diego",      "202 C St",                       "San Diego",         "92101", "City Clerk"),
    ("San Dimas",         "City of San Dimas",      "245 E Bonita Ave",               "San Dimas",         "91773", "City Clerk"),
    ("San Fernando",      "City of San Fernando",   "117 Macneil St",                 "San Fernando",      "91340", "City Clerk"),
    ("San Francisco",     "City and County of San Francisco","1 Dr Carlton B Goodlett Pl","San Francisco", "94102", "City Clerk"),
    ("San Gabriel",       "City of San Gabriel",    "425 S Mission Dr",               "San Gabriel",       "91776", "City Clerk"),
    ("San Jacinto",       "City of San Jacinto",    "595 S San Jacinto Ave",          "San Jacinto",       "92583", "City Clerk"),
    ("San Jose",          "City of San Jose",       "200 E Santa Clara St",           "San Jose",          "95113", "City Clerk"),
    ("San Juan Bautista", "City of San Juan Bautista","311 Second St",                "San Juan Bautista", "95045", "City Clerk"),
    ("San Juan Capistrano","City of San Juan Capistrano","32400 Paseo Adelanto",       "San Juan Capistrano","92675","City Clerk"),
    ("San Leandro",       "City of San Leandro",    "835 E 14th St",                  "San Leandro",       "94577", "City Clerk"),
    ("San Luis Obispo",   "City of San Luis Obispo","990 Palm St",                    "San Luis Obispo",   "93401", "City Clerk"),
    ("San Marcos",        "City of San Marcos",     "1 Civic Center Dr",              "San Marcos",        "92069", "City Clerk"),
    ("San Marino",        "City of San Marino",     "2200 Huntington Dr",             "San Marino",        "91108", "City Clerk"),
    ("San Mateo",         "City of San Mateo",      "330 W 20th Ave",                 "San Mateo",         "94403", "City Clerk"),
    ("San Pablo",         "City of San Pablo",      "13831 San Pablo Ave",            "San Pablo",         "94806", "City Clerk"),
    ("San Rafael",        "City of San Rafael",     "1400 Fifth Ave",                 "San Rafael",        "94901", "City Clerk"),
    ("San Ramon",         "City of San Ramon",      "7000 Bollinger Canyon Rd",       "San Ramon",         "94583", "City Clerk"),
    ("Sanger",            "City of Sanger",         "1700 Seventh St",                "Sanger",            "93657", "City Clerk"),
    ("Santa Ana",         "City of Santa Ana",      "20 Civic Center Plaza",          "Santa Ana",         "92701", "City Clerk"),
    ("Santa Barbara",     "City of Santa Barbara",  "735 Anacapa St",                 "Santa Barbara",     "93101", "City Clerk"),
    ("Santa Clara",       "City of Santa Clara",    "1500 Warburton Ave",             "Santa Clara",       "95050", "City Clerk"),
    ("Santa Clarita",     "City of Santa Clarita",  "23920 Valencia Blvd",            "Santa Clarita",     "91355", "City Clerk"),
    ("Santa Cruz",        "City of Santa Cruz",     "809 Center St",                  "Santa Cruz",        "95060", "City Clerk"),
    ("Santa Maria",       "City of Santa Maria",    "110 E Cook St",                  "Santa Maria",       "93454", "City Clerk"),
    ("Santa Monica",      "City of Santa Monica",   "1685 Main St",                   "Santa Monica",      "90401", "City Clerk"),
    ("Santa Paula",       "City of Santa Paula",    "970 Ventura St",                 "Santa Paula",       "93060", "City Clerk"),
    ("Santa Rosa",        "City of Santa Rosa",     "100 Santa Rosa Ave",             "Santa Rosa",        "95404", "City Clerk"),
    ("Santee",            "City of Santee",         "10601 Magnolia Ave",             "Santee",            "92071", "City Clerk"),
    ("Saratoga",          "City of Saratoga",       "13777 Fruitvale Ave",            "Saratoga",          "95070", "City Clerk"),
    ("Sausalito",         "City of Sausalito",      "420 Litho St",                   "Sausalito",         "94965", "City Clerk"),
    ("Scotts Valley",     "City of Scotts Valley",  "One Civic Center Dr",            "Scotts Valley",     "95066", "City Clerk"),
    ("Seal Beach",        "City of Seal Beach",     "211 Eighth St",                  "Seal Beach",        "90740", "City Clerk"),
    ("Seaside",           "City of Seaside",        "440 Harcourt Ave",               "Seaside",           "93955", "City Clerk"),
    ("Selma",             "City of Selma",          "1710 Tucker St",                 "Selma",             "93662", "City Clerk"),
    ("Shafter",           "City of Shafter",        "336 Pacific Ave",                "Shafter",           "93263", "City Clerk"),
    ("Signal Hill",       "City of Signal Hill",    "2175 Cherry Ave",                "Signal Hill",       "90755", "City Clerk"),
    ("Simi Valley",       "City of Simi Valley",    "2929 Tapo Canyon Rd",            "Simi Valley",       "93063", "City Clerk"),
    ("Solana Beach",      "City of Solana Beach",   "635 S Highway 101",              "Solana Beach",      "92075", "City Clerk"),
    ("Soledad",           "City of Soledad",        "248 Main St",                    "Soledad",           "93960", "City Clerk"),
    ("Solvang",           "City of Solvang",        "1644 Oak St",                    "Solvang",           "93463", "City Clerk"),
    ("Sonoma",            "City of Sonoma",         "No. 1 The Plaza",                "Sonoma",            "95476", "City Clerk"),
    ("Sonora",            "City of Sonora",         "94 N Washington St",             "Sonora",            "95370", "City Clerk"),
    ("South El Monte",    "City of South El Monte", "1415 Santa Anita Ave",           "South El Monte",    "91733", "City Clerk"),
    ("South Gate",        "City of South Gate",     "8650 California Ave",            "South Gate",        "90280", "City Clerk"),
    ("South Lake Tahoe",  "City of South Lake Tahoe","1901 Airport Rd",               "South Lake Tahoe",  "96150", "City Clerk"),
    ("South Pasadena",    "City of South Pasadena", "1414 Mission St",                "South Pasadena",    "91030", "City Clerk"),
    ("South San Francisco","City of South San Francisco","400 Grand Ave",             "South San Francisco","94080","City Clerk"),
    ("St. Helena",        "City of St. Helena",     "1480 Main St",                   "St. Helena",        "94574", "City Clerk"),
    ("Stanton",           "City of Stanton",        "7800 Katella Ave",               "Stanton",           "90680", "City Clerk"),
    ("Stockton",          "City of Stockton",       "425 N El Dorado St",             "Stockton",          "95202", "City Clerk"),
    ("Suisun City",       "City of Suisun City",    "701 Civic Center Blvd",          "Suisun City",       "94585", "City Clerk"),
    ("Sunnyvale",         "City of Sunnyvale",      "456 W Olive Ave",                "Sunnyvale",         "94086", "City Clerk"),
    ("Susanville",        "City of Susanville",     "66 N Lassen St",                 "Susanville",        "96130", "City Clerk"),
    ("Temecula",          "City of Temecula",       "41000 Main St",                  "Temecula",          "92590", "City Clerk"),
    ("Temple City",       "City of Temple City",    "9701 Las Tunas Dr",              "Temple City",       "91780", "City Clerk"),
    ("Thousand Oaks",     "City of Thousand Oaks",  "2100 Thousand Oaks Blvd",        "Thousand Oaks",     "91362", "City Clerk"),
    ("Tiburon",           "Town of Tiburon",        "1505 Tiburon Blvd",              "Tiburon",           "94920", "Town Clerk"),
    ("Torrance",          "City of Torrance",       "3031 Torrance Blvd",             "Torrance",          "90503", "City Clerk"),
    ("Tracy",             "City of Tracy",          "333 Civic Center Plaza",         "Tracy",             "95376", "City Clerk"),
    ("Truckee",           "Town of Truckee",        "10183 Truckee Airport Rd",       "Truckee",           "96161", "Town Clerk"),
    ("Tulare",            "City of Tulare",         "411 E Kern Ave",                 "Tulare",            "93274", "City Clerk"),
    ("Tulelake",          "City of Tulelake",       "591 Main St",                    "Tulelake",          "96134", "City Clerk"),
    ("Turlock",           "City of Turlock",        "156 S Broadway",                 "Turlock",           "95380", "City Clerk"),
    ("Tustin",            "City of Tustin",         "300 Centennial Way",             "Tustin",            "92780", "City Clerk"),
    ("Twentynine Palms",  "City of Twentynine Palms","6136 Adobe Rd",                 "Twentynine Palms",  "92277", "City Clerk"),
    ("Union City",        "City of Union City",     "34009 Alvarado-Niles Rd",        "Union City",        "94587", "City Clerk"),
    ("Upland",            "City of Upland",         "460 N Euclid Ave",               "Upland",            "91786", "City Clerk"),
    ("Vacaville",         "City of Vacaville",      "650 Merchant St",                "Vacaville",         "95688", "City Clerk"),
    ("Vallejo",           "City of Vallejo",        "555 Santa Clara St",             "Vallejo",           "94590", "City Clerk"),
    ("Ventura",           "City of San Buenaventura","501 Poli St",                   "Ventura",           "93001", "City Clerk"),
    ("Vernon",            "City of Vernon",         "4305 Santa Fe Ave",              "Vernon",            "90058", "City Clerk"),
    ("Victorville",       "City of Victorville",    "14343 Civic Dr",                 "Victorville",       "92392", "City Clerk"),
    ("Villa Park",        "City of Villa Park",     "17855 Santiago Blvd",            "Villa Park",        "92861", "City Clerk"),
    ("Visalia",           "City of Visalia",        "707 W Acequia Ave",              "Visalia",           "93291", "City Clerk"),
    ("Vista",             "City of Vista",          "200 Civic Center Dr",            "Vista",             "92084", "City Clerk"),
    ("Walnut",            "City of Walnut",         "21201 La Puente Rd",             "Walnut",            "91789", "City Clerk"),
    ("Walnut Creek",      "City of Walnut Creek",   "1666 N Main St",                 "Walnut Creek",      "94596", "City Clerk"),
    ("Wasco",             "City of Wasco",          "746 8th St",                     "Wasco",             "93280", "City Clerk"),
    ("Waterford",         "City of Waterford",      "101 E St",                       "Waterford",         "95386", "City Clerk"),
    ("Watsonville",       "City of Watsonville",    "275 Main St",                    "Watsonville",       "95076", "City Clerk"),
    ("West Covina",       "City of West Covina",    "1444 W Garvey Ave S",            "West Covina",       "91790", "City Clerk"),
    ("West Hollywood",    "City of West Hollywood", "8300 Santa Monica Blvd",         "West Hollywood",    "90069", "City Clerk"),
    ("West Sacramento",   "City of West Sacramento","1110 W Capitol Ave",             "West Sacramento",   "95691", "City Clerk"),
    ("Westlake Village",  "City of Westlake Village","31200 Oak Crest Dr",            "Westlake Village",  "91361", "City Clerk"),
    ("Westminster",       "City of Westminster",    "8200 Westminster Blvd",          "Westminster",       "92683", "City Clerk"),
    ("Wheatland",         "City of Wheatland",      "111 C St",                       "Wheatland",         "95692", "City Clerk"),
    ("Whittier",          "City of Whittier",       "13230 Penn St",                  "Whittier",          "90602", "City Clerk"),
    ("Wildomar",          "City of Wildomar",       "23873 Clinton Keith Rd",         "Wildomar",          "92595", "City Clerk"),
    ("Williams",          "City of Williams",       "810 E St",                       "Williams",          "95987", "City Clerk"),
    ("Willits",           "City of Willits",        "111 E Commercial St",            "Willits",           "95490", "City Clerk"),
    ("Willow Creek",      "City of Willow Creek",   "City Hall",                      "Willow Creek",      "95573", "City Clerk"),
    ("Willows",           "City of Willows",        "201 N Lassen St",                "Willows",           "95988", "City Clerk"),
    ("Windsor",           "Town of Windsor",        "9291 Old Redwood Hwy",           "Windsor",           "95492", "Town Clerk"),
    ("Winters",           "City of Winters",        "318 First St",                   "Winters",           "95694", "City Clerk"),
    ("Woodlake",          "City of Woodlake",       "150 N Valencia Blvd",            "Woodlake",          "93286", "City Clerk"),
    ("Woodland",          "City of Woodland",       "300 First St",                   "Woodland",          "95695", "City Clerk"),
    ("Woodside",          "Town of Woodside",       "2955 Woodside Rd",               "Woodside",          "94062", "Town Clerk"),
    ("Yorba Linda",       "City of Yorba Linda",    "4845 Casa Loma Ave",             "Yorba Linda",       "92886", "City Clerk"),
    ("Yountville",        "Town of Yountville",     "6550 Yount St",                  "Yountville",        "94599", "Town Clerk"),
    ("Yreka",             "City of Yreka",          "701 Fourth St",                  "Yreka",             "96097", "City Clerk"),
    ("Yuba City",         "City of Yuba City",      "1201 Civic Center Blvd",         "Yuba City",         "95993", "City Clerk"),
    ("Yucaipa",           "City of Yucaipa",        "34272 Yucaipa Blvd",             "Yucaipa",           "92399", "City Clerk"),
    ("Yucca Valley",      "Town of Yucca Valley",   "57090 29 Palms Hwy",             "Yucca Valley",      "92284", "Town Clerk"),
]


def _build_dict():
    out = {}
    for key, name, address, city, zip_, clerk in _CITIES_RAW:
        out[key] = {
            "name":         name,
            "address":      address,
            "city":         city,
            "state":        "CA",
            "zip":          zip_,
            "agent_name":   clerk,
            "agent_title":  clerk,
            "agent_address": address,
            "agent_city":   city,
            "agent_state":  "CA",
            "agent_zip":    zip_,
        }
    return out


CA_MUNICIPALITIES: dict[str, dict] = _build_dict()

ALL_CITIES: list[str] = sorted(CA_MUNICIPALITIES.keys())


def defendant_info(city: str) -> dict:
    """Return defendant dict for the given city name. Falls back to a blank template."""
    if city in CA_MUNICIPALITIES:
        return CA_MUNICIPALITIES[city].copy()
    # Unknown city — return a reasonable blank template
    return {
        "name":          f"City of {city}",
        "address":       "City Hall",
        "city":          city,
        "state":         "CA",
        "zip":           "",
        "agent_name":    "City Clerk",
        "agent_title":   "City Clerk",
        "agent_address": "City Hall",
        "agent_city":    city,
        "agent_state":   "CA",
        "agent_zip":     "",
    }
