"""
California municipalities — 483 verified city hall addresses for service of process.
Sources: official city websites, Nominatim/OSM, Wikipedia (verified 2024).
"""

_DATA = {
    'Adelanto': ('City of Adelanto', '11600 Air Expressway', 'Adelanto', '92301', 'City Clerk'),
    'Agoura Hills': ('City of Agoura Hills', '30001 Ladyface Court', 'Agoura Hills', '91301', 'City Clerk'),
    'Alameda': ('City of Alameda', '2263 Santa Clara Avenue', 'Alameda', '94501', 'City Clerk'),
    'Albany': ('City of Albany', '1000 San Pablo Avenue', 'Albany', '94706', 'City Clerk'),
    'Alhambra': ('City of Alhambra', '111 South First Street', 'Alhambra', '91801', 'City Clerk'),
    'Aliso Viejo': ('City of Aliso Viejo', '12 Journey', 'Aliso Viejo', '92656', 'City Clerk'),
    'Alturas': ('City of Alturas', '525 South Main Street', 'Alturas', '96101', 'City Clerk'),
    'Amador City': ('City of Amador City', '9153 Mill Street', 'Amador City', '95601', 'City Clerk'),
    'American Canyon': ('City of American Canyon', '4381 Broadway Street', 'American Canyon', '94503', 'City Clerk'),
    'Anaheim': ('City of Anaheim', '200 South Anaheim Boulevard', 'Anaheim', '92805', 'City Clerk'),
    'Anderson': ('City of Anderson', '1887 Howard Street', 'Anderson', '96007', 'City Clerk'),
    'Angels Camp': ('City of Angels Camp', '584 South Main Street', 'Angels Camp', '95222', 'City Clerk'),
    'Antioch': ('City of Antioch', '200 H Street', 'Antioch', '94509', 'City Clerk'),
    'Apple Valley': ('Town of Apple Valley', '14955 Dale Evans Parkway', 'Apple Valley', '92307', 'Town Clerk'),
    'Arcadia': ('City of Arcadia', '240 West Huntington Drive', 'Arcadia', '91007', 'City Clerk'),
    'Arcata': ('City of Arcata', '736 F Street', 'Arcata', '95521', 'City Clerk'),
    'Arroyo Grande': ('City of Arroyo Grande', '300 East Branch Street', 'Arroyo Grande', '93420', 'City Clerk'),
    'Artesia': ('City of Artesia', '18747 Clarkdale Avenue', 'Artesia', '90701', 'City Clerk'),
    'Arvin': ('City of Arvin', '200 Campus Drive', 'Arvin', '93203', 'City Clerk'),
    'Atascadero': ('City of Atascadero', '6500 Palma Avenue', 'Atascadero', '93422', 'City Clerk'),
    'Atherton': ('Town of Atherton', '80 Fair Oaks Lane', 'Atherton', '94027', 'Town Clerk'),
    'Atwater': ('City of Atwater', '750 Bellevue Road', 'Atwater', '95301', 'City Clerk'),
    'Auburn': ('City of Auburn', '1225 Lincoln Way', 'Auburn', '95603', 'City Clerk'),
    'Avalon': ('City of Avalon', '410 Avalon Canyon Road', 'Avalon', '90704', 'City Clerk'),
    'Avenal': ('City of Avenal', '919 Skyline Boulevard', 'Avenal', '93204', 'City Clerk'),
    'Azusa': ('City of Azusa', '213 East Foothill Boulevard', 'Azusa', '91702', 'City Clerk'),
    'Bakersfield': ('City of Bakersfield', '1600 Truxtun Avenue', 'Bakersfield', '93301', 'City Clerk'),
    'Baldwin Park': ('City of Baldwin Park', '14403 Pacific Avenue', 'Baldwin Park', '91706', 'City Clerk'),
    'Banning': ('City of Banning', '99 East Ramsey Street', 'Banning', '92220', 'City Clerk'),
    'Barstow': ('City of Barstow', '220 East Mountain View Street', 'Barstow', '92311', 'City Clerk'),
    'Beaumont': ('City of Beaumont', '550 East Sixth Street', 'Beaumont', '92223', 'City Clerk'),
    'Bell': ('City of Bell', '6330 Pine Avenue', 'Bell', '90201', 'City Clerk'),
    'Bell Gardens': ('City of Bell Gardens', '7100 Garfield Avenue', 'Bell Gardens', '90201', 'City Clerk'),
    'Bellflower': ('City of Bellflower', '16600 Civic Center Drive', 'Bellflower', '90706', 'City Clerk'),
    'Belmont': ('City of Belmont', '1 Twin Pines Lane', 'Belmont', '94002', 'City Clerk'),
    'Belvedere': ('City of Belvedere', '450 San Rafael Avenue', 'Belvedere', '94920', 'City Clerk'),
    'Benicia': ('City of Benicia', '250 East L Street', 'Benicia', '94510', 'City Clerk'),
    'Berkeley': ('City of Berkeley', '2180 Milvia Street', 'Berkeley', '94704', 'City Clerk'),
    'Beverly Hills': ('City of Beverly Hills', '455 North Rexford Drive', 'Beverly Hills', '90210', 'City Clerk'),
    'Big Bear Lake': ('City of Big Bear Lake', '39707 Big Bear Boulevard', 'Big Bear Lake', '92315', 'City Clerk'),
    'Biggs': ('City of Biggs', '465 C Street', 'Biggs', '95917', 'City Clerk'),
    'Bishop': ('City of Bishop', '377 West Line Street', 'Bishop', '93514', 'City Clerk'),
    'Blue Lake': ('City of Blue Lake', '111 Greenwood Avenue', 'Blue Lake', '95525', 'City Clerk'),
    'Blythe': ('City of Blythe', '235 North Broadway', 'Blythe', '92225', 'City Clerk'),
    'Bradbury': ('City of Bradbury', '600 Winston Avenue', 'Bradbury', '91008', 'City Clerk'),
    'Brawley': ('City of Brawley', '383 Main Street', 'Brawley', '92227', 'City Clerk'),
    'Brea': ('City of Brea', '1 Civic Center Circle', 'Brea', '92821', 'City Clerk'),
    'Brentwood': ('City of Brentwood', '150 City Park Way', 'Brentwood', '94513', 'City Clerk'),
    'Brisbane': ('City of Brisbane', '50 Park Place', 'Brisbane', '94005', 'City Clerk'),
    'Buellton': ('City of Buellton', '107 West Highway 246', 'Buellton', '93427', 'City Clerk'),
    'Buena Park': ('City of Buena Park', '6650 Beach Boulevard', 'Buena Park', '90620', 'City Clerk'),
    'Burbank': ('City of Burbank', '275 East Olive Avenue', 'Burbank', '91502', 'City Clerk'),
    'Burlingame': ('City of Burlingame', '501 Primrose Road', 'Burlingame', '94010', 'City Clerk'),
    'Calabasas': ('City of Calabasas', '100 Civic Center Way', 'Calabasas', '91302', 'City Clerk'),
    'Calexico': ('City of Calexico', '608 Heber Avenue', 'Calexico', '92231', 'City Clerk'),
    'California City': ('City of California City', '21000 Hacienda Boulevard', 'California City', '93505', 'City Clerk'),
    'Calimesa': ('City of Calimesa', '908 Park Avenue', 'Calimesa', '92320', 'City Clerk'),
    'Calipatria': ('City of Calipatria', '125 North Park Avenue', 'Calipatria', '92233', 'City Clerk'),
    'Calistoga': ('City of Calistoga', '1232 Washington Street', 'Calistoga', '94515', 'City Clerk'),
    'Camarillo': ('City of Camarillo', '601 Carmen Drive', 'Camarillo', '93010', 'City Clerk'),
    'Campbell': ('City of Campbell', '70 North First Street', 'Campbell', '95008', 'City Clerk'),
    'Canyon Lake': ('City of Canyon Lake', '31516 Railroad Canyon Road', 'Canyon Lake', '92587', 'City Clerk'),
    'Capitola': ('City of Capitola', '420 Capitola Avenue', 'Capitola', '95010', 'City Clerk'),
    'Carlsbad': ('City of Carlsbad', '1200 Carlsbad Village Drive', 'Carlsbad', '92008', 'City Clerk'),
    'Carmel-by-the-Sea': ('City of Carmel-by-the-Sea', 'Monte Verde at Seventh', 'Carmel-by-the-Sea', '93921', 'City Clerk'),
    'Carpinteria': ('City of Carpinteria', '5775 Carpinteria Avenue', 'Carpinteria', '93013', 'City Clerk'),
    'Carson': ('City of Carson', '701 East Carson Street', 'Carson', '90745', 'City Clerk'),
    'Cathedral City': ('City of Cathedral City', '68700 Avenida Lalo Guerrero', 'Cathedral City', '92234', 'City Clerk'),
    'Ceres': ('City of Ceres', '2720 Second Street', 'Ceres', '95307', 'City Clerk'),
    'Cerritos': ('City of Cerritos', '18125 Bloomfield Avenue', 'Cerritos', '90703', 'City Clerk'),
    'Chico': ('City of Chico', '411 Main Street', 'Chico', '95928', 'City Clerk'),
    'Chino': ('City of Chino', '13220 Central Avenue', 'Chino', '91710', 'City Clerk'),
    'Chino Hills': ('City of Chino Hills', '14000 City Center Drive', 'Chino Hills', '91709', 'City Clerk'),
    'Chowchilla': ('City of Chowchilla', '130 South Second Street', 'Chowchilla', '93610', 'City Clerk'),
    'Chula Vista': ('City of Chula Vista', '276 Fourth Avenue', 'Chula Vista', '91910', 'City Clerk'),
    'Citrus Heights': ('City of Citrus Heights', '6237 Fountain Square Drive', 'Citrus Heights', '95621', 'City Clerk'),
    'City of Industry': ('City of Industry', '15625 East Stafford Street', 'City of Industry', '91744', 'City Clerk'),
    'Claremont': ('City of Claremont', '207 Harvard Avenue', 'Claremont', '91711', 'City Clerk'),
    'Clayton': ('City of Clayton', '10 Eagle Road', 'Clayton', '94517', 'City Clerk'),
    'Clearlake': ('City of Clearlake', '14050 Olympic Drive', 'Clearlake', '95422', 'City Clerk'),
    'Cloverdale': ('City of Cloverdale', '124 North Cloverdale Boulevard', 'Cloverdale', '95425', 'City Clerk'),
    'Clovis': ('City of Clovis', '1033 Fifth Street', 'Clovis', '93612', 'City Clerk'),
    'Coachella': ('City of Coachella', '1515 Sixth Street', 'Coachella', '92236', 'City Clerk'),
    'Coalinga': ('City of Coalinga', '155 West Durian Avenue', 'Coalinga', '93210', 'City Clerk'),
    'Colfax': ('City of Colfax', '33 South Main Street', 'Colfax', '95713', 'City Clerk'),
    'Colma': ('Town of Colma', '1198 El Camino Real', 'Colma', '94014', 'Town Clerk'),
    'Colton': ('City of Colton', '650 North La Cadena Drive', 'Colton', '92324', 'City Clerk'),
    'Colusa': ('City of Colusa', '425 Webster Street', 'Colusa', '95932', 'City Clerk'),
    'Commerce': ('City of Commerce', '2535 Commerce Way', 'Commerce', '90040', 'City Clerk'),
    'Compton': ('City of Compton', '205 South Willowbrook Avenue', 'Compton', '90220', 'City Clerk'),
    'Concord': ('City of Concord', '1950 Parkside Drive', 'Concord', '94519', 'City Clerk'),
    'Corcoran': ('City of Corcoran', '832 Whitley Avenue', 'Corcoran', '93212', 'City Clerk'),
    'Corning': ('City of Corning', '794 Third Street', 'Corning', '96021', 'City Clerk'),
    'Corona': ('City of Corona', '400 South Vicentia Avenue', 'Corona', '92882', 'City Clerk'),
    'Coronado': ('City of Coronado', '1825 Strand Way', 'Coronado', '92118', 'City Clerk'),
    'Corte Madera': ('Town of Corte Madera', '300 Tamalpais Drive', 'Corte Madera', '94925', 'Town Clerk'),
    'Costa Mesa': ('City of Costa Mesa', '77 Fair Drive', 'Costa Mesa', '92626', 'City Clerk'),
    'Cotati': ('City of Cotati', '201 West Sierra Avenue', 'Cotati', '94931', 'City Clerk'),
    'Covina': ('City of Covina', '125 East College Street', 'Covina', '91723', 'City Clerk'),
    'Crescent City': ('City of Crescent City', '377 J Street', 'Crescent City', '95531', 'City Clerk'),
    'Cudahy': ('City of Cudahy', '5220 Santa Ana Street', 'Cudahy', '90201', 'City Clerk'),
    'Culver City': ('City of Culver City', '9770 Culver Boulevard', 'Culver City', '90232', 'City Clerk'),
    'Cupertino': ('City of Cupertino', '10300 Torre Avenue', 'Cupertino', '95014', 'City Clerk'),
    'Cypress': ('City of Cypress', '5275 Orange Avenue', 'Cypress', '90630', 'City Clerk'),
    'Daly City': ('City of Daly City', '333 90th Street', 'Daly City', '94015', 'City Clerk'),
    'Dana Point': ('City of Dana Point', '33282 Golden Lantern', 'Dana Point', '92629', 'City Clerk'),
    'Danville': ('Town of Danville', '510 La Gonda Way', 'Danville', '94526', 'Town Clerk'),
    'Davis': ('City of Davis', '23 Russell Boulevard', 'Davis', '95616', 'City Clerk'),
    'Del Mar': ('City of Del Mar', '1050 Camino Del Mar', 'Del Mar', '92014', 'City Clerk'),
    'Del Rey Oaks': ('City of Del Rey Oaks', '650 Canyon Del Rey', 'Del Rey Oaks', '93940', 'City Clerk'),
    'Delano': ('City of Delano', '1015 11th Avenue', 'Delano', '93215', 'City Clerk'),
    'Desert Hot Springs': ('City of Desert Hot Springs', '65950 Pierson Boulevard', 'Desert Hot Springs', '92240', 'City Clerk'),
    'Diamond Bar': ('City of Diamond Bar', '21810 Copley Drive', 'Diamond Bar', '91765', 'City Clerk'),
    'Dinuba': ('City of Dinuba', '405 East El Monte Way', 'Dinuba', '93618', 'City Clerk'),
    'Dixon': ('City of Dixon', '600 East A Street', 'Dixon', '95620', 'City Clerk'),
    'Dorris': ('City of Dorris', '116 South Main Street', 'Dorris', '96023', 'City Clerk'),
    'Dos Palos': ('City of Dos Palos', '1546 Golden Gate Avenue', 'Dos Palos', '93620', 'City Clerk'),
    'Downey': ('City of Downey', '11111 Brookshire Avenue', 'Downey', '90241', 'City Clerk'),
    'Duarte': ('City of Duarte', '1600 Huntington Drive', 'Duarte', '91010', 'City Clerk'),
    'Dublin': ('City of Dublin', '100 Civic Plaza', 'Dublin', '94568', 'City Clerk'),
    'Dunsmuir': ('City of Dunsmuir', '5915 Dunsmuir Avenue', 'Dunsmuir', '96025', 'City Clerk'),
    'East Palo Alto': ('City of East Palo Alto', '1960 Tate Street', 'East Palo Alto', '94303', 'City Clerk'),
    'Eastvale': ('City of Eastvale', '12363 Limonite Avenue', 'Eastvale', '91752', 'City Clerk'),
    'El Cajon': ('City of El Cajon', '200 Civic Center Way', 'El Cajon', '92020', 'City Clerk'),
    'El Centro': ('City of El Centro', '1275 Main Street', 'El Centro', '92243', 'City Clerk'),
    'El Cerrito': ('City of El Cerrito', '10890 San Pablo Avenue', 'El Cerrito', '94530', 'City Clerk'),
    'El Monte': ('City of El Monte', '11333 Valley Boulevard', 'El Monte', '91731', 'City Clerk'),
    'El Segundo': ('City of El Segundo', '350 Main Street', 'El Segundo', '90245', 'City Clerk'),
    'Elk Grove': ('City of Elk Grove', '8401 Laguna Palms Way', 'Elk Grove', '95758', 'City Clerk'),
    'Emeryville': ('City of Emeryville', '1333 Park Avenue', 'Emeryville', '94608', 'City Clerk'),
    'Encinitas': ('City of Encinitas', '505 South Vulcan Avenue', 'Encinitas', '92024', 'City Clerk'),
    'Escalon': ('City of Escalon', '2060 McHenry Avenue', 'Escalon', '95320', 'City Clerk'),
    'Escondido': ('City of Escondido', '201 North Broadway', 'Escondido', '92025', 'City Clerk'),
    'Etna': ('City of Etna', '100 Diggles Street', 'Etna', '96027', 'City Clerk'),
    'Eureka': ('City of Eureka', '531 K Street', 'Eureka', '95501', 'City Clerk'),
    'Exeter': ('City of Exeter', '137 North F Street', 'Exeter', '93221', 'City Clerk'),
    'Fairfax': ('Town of Fairfax', '142 Bolinas Road', 'Fairfax', '94930', 'Town Clerk'),
    'Fairfield': ('City of Fairfield', '1000 Webster Street', 'Fairfield', '94533', 'City Clerk'),
    'Farmersville': ('City of Farmersville', '909 West Visalia Road', 'Farmersville', '93223', 'City Clerk'),
    'Ferndale': ('City of Ferndale', '834 Main Street', 'Ferndale', '95536', 'City Clerk'),
    'Fillmore': ('City of Fillmore', '250 Central Avenue', 'Fillmore', '93015', 'City Clerk'),
    'Firebaugh': ('City of Firebaugh', '1133 P Street', 'Firebaugh', '93622', 'City Clerk'),
    'Folsom': ('City of Folsom', '50 Natoma Street', 'Folsom', '95630', 'City Clerk'),
    'Fontana': ('City of Fontana', '8353 Sierra Avenue', 'Fontana', '92335', 'City Clerk'),
    'Fort Bragg': ('City of Fort Bragg', '416 North Franklin Street', 'Fort Bragg', '95437', 'City Clerk'),
    'Fort Jones': ('Town of Fort Jones', '11 Court Street', 'Fort Jones', '96032', 'Town Clerk'),
    'Fortuna': ('City of Fortuna', '621 11th Street', 'Fortuna', '95540', 'City Clerk'),
    'Foster City': ('City of Foster City', '610 Foster City Boulevard', 'Foster City', '94404', 'City Clerk'),
    'Fountain Valley': ('City of Fountain Valley', '10200 Slater Avenue', 'Fountain Valley', '92708', 'City Clerk'),
    'Fowler': ('City of Fowler', '128 East Adams Avenue', 'Fowler', '93625', 'City Clerk'),
    'Fremont': ('City of Fremont', '3300 Capitol Avenue', 'Fremont', '94538', 'City Clerk'),
    'Fresno': ('City of Fresno', '2600 Fresno Street', 'Fresno', '93721', 'City Clerk'),
    'Fullerton': ('City of Fullerton', '303 West Commonwealth Avenue', 'Fullerton', '92832', 'City Clerk'),
    'Galt': ('City of Galt', '380 Civic Drive', 'Galt', '95632', 'City Clerk'),
    'Garden Grove': ('City of Garden Grove', '11222 Acacia Parkway', 'Garden Grove', '92840', 'City Clerk'),
    'Gardena': ('City of Gardena', '1700 West 162nd Street', 'Gardena', '90247', 'City Clerk'),
    'Gilroy': ('City of Gilroy', '7351 Rosanna Street', 'Gilroy', '95020', 'City Clerk'),
    'Glendale': ('City of Glendale', '613 East Broadway', 'Glendale', '91206', 'City Clerk'),
    'Glendora': ('City of Glendora', '116 East Foothill Boulevard', 'Glendora', '91741', 'City Clerk'),
    'Goleta': ('City of Goleta', '130 Cremona Drive', 'Goleta', '93117', 'City Clerk'),
    'Gonzales': ('City of Gonzales', '147 Fourth Street', 'Gonzales', '93926', 'City Clerk'),
    'Grand Terrace': ('City of Grand Terrace', '22795 Barton Road', 'Grand Terrace', '92313', 'City Clerk'),
    'Grass Valley': ('City of Grass Valley', '125 East Main Street', 'Grass Valley', '95945', 'City Clerk'),
    'Greenfield': ('City of Greenfield', '599 El Camino Real', 'Greenfield', '93927', 'City Clerk'),
    'Gridley': ('City of Gridley', '685 Kentucky Street', 'Gridley', '95948', 'City Clerk'),
    'Grover Beach': ('City of Grover Beach', '154 South 8th Street', 'Grover Beach', '93433', 'City Clerk'),
    'Guadalupe': ('City of Guadalupe', '918 Obispo Street', 'Guadalupe', '93434', 'City Clerk'),
    'Gustine': ('City of Gustine', '350 5th Street', 'Gustine', '95322', 'City Clerk'),
    'Half Moon Bay': ('City of Half Moon Bay', '501 Main Street', 'Half Moon Bay', '94019', 'City Clerk'),
    'Hanford': ('City of Hanford', '317 North Douty Street', 'Hanford', '93230', 'City Clerk'),
    'Hawaiian Gardens': ('City of Hawaiian Gardens', '21815 Pioneer Boulevard', 'Hawaiian Gardens', '90716', 'City Clerk'),
    'Hawthorne': ('City of Hawthorne', '4455 West 126th Street', 'Hawthorne', '90250', 'City Clerk'),
    'Hayward': ('City of Hayward', '777 B Street', 'Hayward', '94541', 'City Clerk'),
    'Healdsburg': ('City of Healdsburg', '401 Grove Street', 'Healdsburg', '95448', 'City Clerk'),
    'Hemet': ('City of Hemet', '445 East Florida Avenue', 'Hemet', '92543', 'City Clerk'),
    'Hercules': ('City of Hercules', '111 Civic Drive', 'Hercules', '94547', 'City Clerk'),
    'Hermosa Beach': ('City of Hermosa Beach', '1315 Valley Drive', 'Hermosa Beach', '90254', 'City Clerk'),
    'Hesperia': ('City of Hesperia', '9700 Seventh Avenue', 'Hesperia', '92345', 'City Clerk'),
    'Hidden Hills': ('City of Hidden Hills', '6165 Spring Valley Road', 'Hidden Hills', '91302', 'City Clerk'),
    'Highland': ('City of Highland', '27215 Base Line', 'Highland', '92346', 'City Clerk'),
    'Hillsborough': ('Town of Hillsborough', '1600 Floribunda Avenue', 'Hillsborough', '94010', 'Town Clerk'),
    'Hollister': ('City of Hollister', '375 Fifth Street', 'Hollister', '95023', 'City Clerk'),
    'Holtville': ('City of Holtville', '121 West Fifth Street', 'Holtville', '92250', 'City Clerk'),
    'Hughson': ('City of Hughson', '7018 Pine Street', 'Hughson', '95326', 'City Clerk'),
    'Huntington Beach': ('City of Huntington Beach', '2000 Main Street', 'Huntington Beach', '92648', 'City Clerk'),
    'Huntington Park': ('City of Huntington Park', '6550 Miles Avenue', 'Huntington Park', '90255', 'City Clerk'),
    'Huron': ('City of Huron', '36311 Lassen Avenue', 'Huron', '93234', 'City Clerk'),
    'Imperial': ('City of Imperial', '420 South Imperial Avenue', 'Imperial', '92251', 'City Clerk'),
    'Imperial Beach': ('City of Imperial Beach', '825 Imperial Beach Boulevard', 'Imperial Beach', '91932', 'City Clerk'),
    'Indian Wells': ('City of Indian Wells', '44950 Eldorado Drive', 'Indian Wells', '92210', 'City Clerk'),
    'Indio': ('City of Indio', '100 Civic Center Mall', 'Indio', '92201', 'City Clerk'),
    'Inglewood': ('City of Inglewood', '1 Manchester Boulevard', 'Inglewood', '90301', 'City Clerk'),
    'Ione': ('City of Ione', '1 East Main Street', 'Ione', '95640', 'City Clerk'),
    'Irvine': ('City of Irvine', '1 Civic Center Plaza', 'Irvine', '92606', 'City Clerk'),
    'Irwindale': ('City of Irwindale', '5050 Irwindale Avenue', 'Irwindale', '91010', 'City Clerk'),
    'Isleton': ('City of Isleton', '100 Second Street', 'Isleton', '95641', 'City Clerk'),
    'Jackson': ('City of Jackson', '33 Broadway', 'Jackson', '95642', 'City Clerk'),
    'Jurupa Valley': ('City of Jurupa Valley', '8930 Limonite Avenue', 'Jurupa Valley', '92509', 'City Clerk'),
    'Kerman': ('City of Kerman', '850 South Madera Avenue', 'Kerman', '93630', 'City Clerk'),
    'King City': ('City of King City', '212 South Vanderhurst Avenue', 'King City', '93930', 'City Clerk'),
    'Kingsburg': ('City of Kingsburg', '1401 Draper Street', 'Kingsburg', '93631', 'City Clerk'),
    'La Cañada Flintridge': ('City of La Cañada Flintridge', '1327 Foothill Boulevard', 'La Cañada Flintridge', '91011', 'City Clerk'),
    'La Habra': ('City of La Habra', '110 East La Habra Boulevard', 'La Habra', '90631', 'City Clerk'),
    'La Habra Heights': ('City of La Habra Heights', '1245 North Hacienda Road', 'La Habra Heights', '90631', 'City Clerk'),
    'La Mesa': ('City of La Mesa', '8130 Allison Avenue', 'La Mesa', '91942', 'City Clerk'),
    'La Mirada': ('City of La Mirada', '13700 La Mirada Boulevard', 'La Mirada', '90638', 'City Clerk'),
    'La Palma': ('City of La Palma', '7822 Walker Street', 'La Palma', '90623', 'City Clerk'),
    'La Puente': ('City of La Puente', '15900 East Main Street', 'La Puente', '91744', 'City Clerk'),
    'La Quinta': ('City of La Quinta', '78495 Calle Tampico', 'La Quinta', '92253', 'City Clerk'),
    'La Verne': ('City of La Verne', '3660 D Street', 'La Verne', '91750', 'City Clerk'),
    'Lafayette': ('City of Lafayette', '3675 Mount Diablo Boulevard', 'Lafayette', '94549', 'City Clerk'),
    'Laguna Beach': ('City of Laguna Beach', '505 Forest Avenue', 'Laguna Beach', '92651', 'City Clerk'),
    'Laguna Hills': ('City of Laguna Hills', '24035 El Toro Road', 'Laguna Hills', '92653', 'City Clerk'),
    'Laguna Niguel': ('City of Laguna Niguel', '30111 Crown Valley Parkway', 'Laguna Niguel', '92677', 'City Clerk'),
    'Laguna Woods': ('City of Laguna Woods', '24264 El Toro Road', 'Laguna Woods', '92637', 'City Clerk'),
    'Lake Elsinore': ('City of Lake Elsinore', '130 South Main Street', 'Lake Elsinore', '92530', 'City Clerk'),
    'Lake Forest': ('City of Lake Forest', '100 Civic Center Drive', 'Lake Forest', '92630', 'City Clerk'),
    'Lakeport': ('City of Lakeport', '225 Park Street', 'Lakeport', '95453', 'City Clerk'),
    'Lakewood': ('City of Lakewood', '5050 Clark Avenue', 'Lakewood', '90712', 'City Clerk'),
    'Lancaster': ('City of Lancaster', '44933 Fern Avenue', 'Lancaster', '93534', 'City Clerk'),
    'Larkspur': ('City of Larkspur', '400 Magnolia Avenue', 'Larkspur', '94939', 'City Clerk'),
    'Lathrop': ('City of Lathrop', '390 Towne Centre Drive', 'Lathrop', '95330', 'City Clerk'),
    'Lawndale': ('City of Lawndale', '14717 Burin Avenue', 'Lawndale', '90260', 'City Clerk'),
    'Lemon Grove': ('City of Lemon Grove', '3232 Main Street', 'Lemon Grove', '91945', 'City Clerk'),
    'Lemoore': ('City of Lemoore', '119 Fox Street', 'Lemoore', '93245', 'City Clerk'),
    'Lincoln': ('City of Lincoln', '600 Sixth Street', 'Lincoln', '95648', 'City Clerk'),
    'Lindsay': ('City of Lindsay', '251 East Honolulu Street', 'Lindsay', '93247', 'City Clerk'),
    'Live Oak': ('City of Live Oak', '9955 Live Oak Boulevard', 'Live Oak', '95953', 'City Clerk'),
    'Livermore': ('City of Livermore', '1052 South Livermore Avenue', 'Livermore', '94550', 'City Clerk'),
    'Livingston': ('City of Livingston', '1416 C Street', 'Livingston', '95334', 'City Clerk'),
    'Lodi': ('City of Lodi', '221 West Pine Street', 'Lodi', '95240', 'City Clerk'),
    'Loma Linda': ('City of Loma Linda', '25541 Barton Road', 'Loma Linda', '92354', 'City Clerk'),
    'Lomita': ('City of Lomita', '24300 Narbonne Avenue', 'Lomita', '90717', 'City Clerk'),
    'Lompoc': ('City of Lompoc', '100 Civic Center Plaza', 'Lompoc', '93436', 'City Clerk'),
    'Long Beach': ('City of Long Beach', '411 West Ocean Boulevard', 'Long Beach', '90802', 'City Clerk'),
    'Loomis': ('Town of Loomis', '6140 Horseshoe Bar Road', 'Loomis', '95650', 'Town Clerk'),
    'Los Alamitos': ('City of Los Alamitos', '3191 Katella Avenue', 'Los Alamitos', '90720', 'City Clerk'),
    'Los Altos': ('City of Los Altos', '1 North San Antonio Road', 'Los Altos', '94022', 'City Clerk'),
    'Los Altos Hills': ('Town of Los Altos Hills', '26379 Fremont Road', 'Los Altos Hills', '94022', 'Town Clerk'),
    'Los Angeles': ('City of Los Angeles', '200 North Spring Street', 'Los Angeles', '90012', 'City Clerk'),
    'Los Banos': ('City of Los Banos', '520 J Street', 'Los Banos', '93635', 'City Clerk'),
    'Los Gatos': ('Town of Los Gatos', '110 East Main Street', 'Los Gatos', '95030', 'Town Clerk'),
    'Loyalton': ('City of Loyalton', '700 Third Street', 'Loyalton', '96118', 'City Clerk'),
    'Lynwood': ('City of Lynwood', '11330 Bullis Road', 'Lynwood', '90262', 'City Clerk'),
    'Madera': ('City of Madera', '205 West 4th Street', 'Madera', '93637', 'City Clerk'),
    'Malibu': ('City of Malibu', '23825 Stuart Ranch Road', 'Malibu', '90265', 'City Clerk'),
    'Mammoth Lakes': ('Town of Mammoth Lakes', '437 Old Mammoth Road', 'Mammoth Lakes', '93546', 'Town Clerk'),
    'Manhattan Beach': ('City of Manhattan Beach', '1400 Highland Avenue', 'Manhattan Beach', '90266', 'City Clerk'),
    'Manteca': ('City of Manteca', '1001 West Center Street', 'Manteca', '95337', 'City Clerk'),
    'Maricopa': ('City of Maricopa', '100 East California Avenue', 'Maricopa', '93252', 'City Clerk'),
    'Marina': ('City of Marina', '211 Hillcrest Avenue', 'Marina', '93933', 'City Clerk'),
    'Martinez': ('City of Martinez', '525 Henrietta Street', 'Martinez', '94553', 'City Clerk'),
    'Marysville': ('City of Marysville', '526 C Street', 'Marysville', '95901', 'City Clerk'),
    'Maywood': ('City of Maywood', '4319 East Slauson Avenue', 'Maywood', '90270', 'City Clerk'),
    'McFarland': ('City of McFarland', '401 West Kern Avenue', 'McFarland', '93250', 'City Clerk'),
    'Mendota': ('City of Mendota', '643 Quince Street', 'Mendota', '93640', 'City Clerk'),
    'Menifee': ('City of Menifee', '29714 Haun Road', 'Menifee', '92586', 'City Clerk'),
    'Menlo Park': ('City of Menlo Park', '701 Laurel Street', 'Menlo Park', '94025', 'City Clerk'),
    'Merced': ('City of Merced', '678 West 18th Street', 'Merced', '95340', 'City Clerk'),
    'Mill Valley': ('City of Mill Valley', '26 Corte Madera Avenue', 'Mill Valley', '94941', 'City Clerk'),
    'Millbrae': ('City of Millbrae', '621 Magnolia Avenue', 'Millbrae', '94030', 'City Clerk'),
    'Milpitas': ('City of Milpitas', '455 East Calaveras Boulevard', 'Milpitas', '95035', 'City Clerk'),
    'Mission Viejo': ('City of Mission Viejo', '200 Civic Center', 'Mission Viejo', '92691', 'City Clerk'),
    'Modesto': ('City of Modesto', '1010 10th Street', 'Modesto', '95354', 'City Clerk'),
    'Monrovia': ('City of Monrovia', '415 South Ivy Avenue', 'Monrovia', '91016', 'City Clerk'),
    'Montague': ('City of Montague', '111 South 12th Street', 'Montague', '96064', 'City Clerk'),
    'Montclair': ('City of Montclair', '5111 Benito Street', 'Montclair', '91763', 'City Clerk'),
    'Monte Sereno': ('City of Monte Sereno', '18041 Saratoga-Los Gatos Road', 'Monte Sereno', '95030', 'City Clerk'),
    'Montebello': ('City of Montebello', '1600 West Beverly Boulevard', 'Montebello', '90640', 'City Clerk'),
    'Monterey': ('City of Monterey', '580 Pacific Street', 'Monterey', '93940', 'City Clerk'),
    'Monterey Park': ('City of Monterey Park', '320 West Newmark Avenue', 'Monterey Park', '91754', 'City Clerk'),
    'Moorpark': ('City of Moorpark', '799 Moorpark Avenue', 'Moorpark', '93021', 'City Clerk'),
    'Moraga': ('Town of Moraga', '329 Rheem Boulevard', 'Moraga', '94556', 'Town Clerk'),
    'Moreno Valley': ('City of Moreno Valley', '14177 Frederick Street', 'Moreno Valley', '92552', 'City Clerk'),
    'Morgan Hill': ('City of Morgan Hill', '17575 Peak Avenue', 'Morgan Hill', '95037', 'City Clerk'),
    'Morro Bay': ('City of Morro Bay', '595 Harbor Street', 'Morro Bay', '93442', 'City Clerk'),
    'Mount Shasta': ('City of Mount Shasta', '305 North Mount Shasta Boulevard', 'Mount Shasta', '96067', 'City Clerk'),
    'Mountain House': ('City of Mountain House', '198 East Main Street', 'Mountain House', '95391', 'City Clerk'),
    'Mountain View': ('City of Mountain View', '500 Castro Street', 'Mountain View', '94041', 'City Clerk'),
    'Murrieta': ('City of Murrieta', '1 Town Square', 'Murrieta', '92562', 'City Clerk'),
    'Napa': ('City of Napa', '955 School Street', 'Napa', '94559', 'City Clerk'),
    'National City': ('City of National City', '1243 National City Boulevard', 'National City', '91950', 'City Clerk'),
    'Needles': ('City of Needles', '817 Third Street', 'Needles', '92363', 'City Clerk'),
    'Nevada City': ('City of Nevada City', '317 Broad Street', 'Nevada City', '95959', 'City Clerk'),
    'Newark': ('City of Newark', '37101 Newark Boulevard', 'Newark', '94560', 'City Clerk'),
    'Newman': ('City of Newman', '1162 Main Street', 'Newman', '95360', 'City Clerk'),
    'Newport Beach': ('City of Newport Beach', '100 Civic Center Drive', 'Newport Beach', '92660', 'City Clerk'),
    'Norco': ('City of Norco', '2870 Clark Avenue', 'Norco', '92860', 'City Clerk'),
    'Norwalk': ('City of Norwalk', '12700 Norwalk Boulevard', 'Norwalk', '90650', 'City Clerk'),
    'Novato': ('City of Novato', '922 Machin Avenue', 'Novato', '94945', 'City Clerk'),
    'Oakdale': ('City of Oakdale', '280 North Third Avenue', 'Oakdale', '95361', 'City Clerk'),
    'Oakland': ('City of Oakland', '1 Frank H Ogawa Plaza', 'Oakland', '94612', 'City Clerk'),
    'Oakley': ('City of Oakley', '3231 Main Street', 'Oakley', '94561', 'City Clerk'),
    'Oceanside': ('City of Oceanside', '300 North Coast Highway', 'Oceanside', '92054', 'City Clerk'),
    'Ojai': ('City of Ojai', '401 South Ventura Street', 'Ojai', '93023', 'City Clerk'),
    'Ontario': ('City of Ontario', '303 East B Street', 'Ontario', '91764', 'City Clerk'),
    'Orange': ('City of Orange', '300 East Chapman Avenue', 'Orange', '92866', 'City Clerk'),
    'Orange Cove': ('City of Orange Cove', '633 6th Street', 'Orange Cove', '93646', 'City Clerk'),
    'Orinda': ('City of Orinda', '22 Orinda Way', 'Orinda', '94563', 'City Clerk'),
    'Orland': ('City of Orland', '815 Fourth Street', 'Orland', '95963', 'City Clerk'),
    'Oroville': ('City of Oroville', '1735 Montgomery Street', 'Oroville', '95965', 'City Clerk'),
    'Oxnard': ('City of Oxnard', '305 West Third Street', 'Oxnard', '93030', 'City Clerk'),
    'Pacific Grove': ('City of Pacific Grove', '300 Forest Avenue', 'Pacific Grove', '93950', 'City Clerk'),
    'Pacifica': ('City of Pacifica', '170 Santa Maria Avenue', 'Pacifica', '94044', 'City Clerk'),
    'Palm Desert': ('City of Palm Desert', '73510 Fred Waring Drive', 'Palm Desert', '92260', 'City Clerk'),
    'Palm Springs': ('City of Palm Springs', '3200 East Tahquitz Canyon Way', 'Palm Springs', '92262', 'City Clerk'),
    'Palmdale': ('City of Palmdale', '38300 Sierra Highway', 'Palmdale', '93550', 'City Clerk'),
    'Palo Alto': ('City of Palo Alto', '250 Hamilton Avenue', 'Palo Alto', '94301', 'City Clerk'),
    'Palos Verdes Estates': ('City of Palos Verdes Estates', '340 Palos Verdes Drive West', 'Palos Verdes Estates', '90274', 'City Clerk'),
    'Paradise': ('Town of Paradise', '5555 Skyway', 'Paradise', '95969', 'Town Clerk'),
    'Paramount': ('City of Paramount', '16400 Colorado Avenue', 'Paramount', '90723', 'City Clerk'),
    'Parlier': ('City of Parlier', '1100 East Parlier Avenue', 'Parlier', '93648', 'City Clerk'),
    'Pasadena': ('City of Pasadena', '100 North Garfield Avenue', 'Pasadena', '91109', 'City Clerk'),
    'Paso Robles': ('City of Paso Robles', '1000 Spring Street', 'Paso Robles', '93446', 'City Clerk'),
    'Patterson': ('City of Patterson', '1 Plaza', 'Patterson', '95363', 'City Clerk'),
    'Perris': ('City of Perris', '101 North D Street', 'Perris', '92570', 'City Clerk'),
    'Petaluma': ('City of Petaluma', '11 English Street', 'Petaluma', '94952', 'City Clerk'),
    'Pico Rivera': ('City of Pico Rivera', '6615 Passons Boulevard', 'Pico Rivera', '90660', 'City Clerk'),
    'Piedmont': ('City of Piedmont', '120 Vista Avenue', 'Piedmont', '94611', 'City Clerk'),
    'Pinole': ('City of Pinole', '2131 Pear Street', 'Pinole', '94564', 'City Clerk'),
    'Pismo Beach': ('City of Pismo Beach', '760 Mattie Road', 'Pismo Beach', '93449', 'City Clerk'),
    'Pittsburg': ('City of Pittsburg', '65 Civic Avenue', 'Pittsburg', '94565', 'City Clerk'),
    'Placentia': ('City of Placentia', '401 East Chapman Avenue', 'Placentia', '92870', 'City Clerk'),
    'Placerville': ('City of Placerville', '3101 Center Street', 'Placerville', '95667', 'City Clerk'),
    'Pleasant Hill': ('City of Pleasant Hill', '100 Gregory Lane', 'Pleasant Hill', '94523', 'City Clerk'),
    'Pleasanton': ('City of Pleasanton', '200 Old Bernal Avenue', 'Pleasanton', '94566', 'City Clerk'),
    'Plymouth': ('City of Plymouth', '9426 Main Street', 'Plymouth', '95669', 'City Clerk'),
    'Point Arena': ('City of Point Arena', '451 School Street', 'Point Arena', '95468', 'City Clerk'),
    'Pomona': ('City of Pomona', '505 South Garey Avenue', 'Pomona', '91766', 'City Clerk'),
    'Port Hueneme': ('City of Port Hueneme', '250 North Ventura Road', 'Port Hueneme', '93041', 'City Clerk'),
    'Porterville': ('City of Porterville', '291 North Main Street', 'Porterville', '93257', 'City Clerk'),
    'Portola': ('City of Portola', '35 Third Avenue', 'Portola', '96122', 'City Clerk'),
    'Portola Valley': ('Town of Portola Valley', '765 Portola Road', 'Portola Valley', '94028', 'Town Clerk'),
    'Poway': ('City of Poway', '13325 Civic Center Drive', 'Poway', '92064', 'City Clerk'),
    'Rancho Cordova': ('City of Rancho Cordova', '2729 Prospect Park Drive', 'Rancho Cordova', '95670', 'City Clerk'),
    'Rancho Cucamonga': ('City of Rancho Cucamonga', '10500 Civic Center Drive', 'Rancho Cucamonga', '91730', 'City Clerk'),
    'Rancho Mirage': ('City of Rancho Mirage', '69825 Highway 111', 'Rancho Mirage', '92270', 'City Clerk'),
    'Rancho Palos Verdes': ('City of Rancho Palos Verdes', '30940 Hawthorne Boulevard', 'Rancho Palos Verdes', '90275', 'City Clerk'),
    'Rancho Santa Margarita': ('City of Rancho Santa Margarita', '22112 El Paseo', 'Rancho Santa Margarita', '92688', 'City Clerk'),
    'Red Bluff': ('City of Red Bluff', '555 Washington Street', 'Red Bluff', '96080', 'City Clerk'),
    'Redding': ('City of Redding', '777 Cypress Avenue', 'Redding', '96001', 'City Clerk'),
    'Redlands': ('City of Redlands', '35 Cajon Street', 'Redlands', '92373', 'City Clerk'),
    'Redondo Beach': ('City of Redondo Beach', '415 Diamond Street', 'Redondo Beach', '90277', 'City Clerk'),
    'Redwood City': ('City of Redwood City', '1017 Middlefield Road', 'Redwood City', '94063', 'City Clerk'),
    'Reedley': ('City of Reedley', '845 G Street', 'Reedley', '93654', 'City Clerk'),
    'Rialto': ('City of Rialto', '150 South Palm Avenue', 'Rialto', '92376', 'City Clerk'),
    'Richmond': ('City of Richmond', '450 Civic Center Plaza', 'Richmond', '94804', 'City Clerk'),
    'Ridgecrest': ('City of Ridgecrest', '100 West California Avenue', 'Ridgecrest', '93555', 'City Clerk'),
    'Rio Dell': ('City of Rio Dell', '675 Wildwood Avenue', 'Rio Dell', '95562', 'City Clerk'),
    'Rio Vista': ('City of Rio Vista', '1 Main Street', 'Rio Vista', '94571', 'City Clerk'),
    'Ripon': ('City of Ripon', '259 Wilma Avenue', 'Ripon', '95366', 'City Clerk'),
    'Riverbank': ('City of Riverbank', '6707 Third Street', 'Riverbank', '95367', 'City Clerk'),
    'Riverside': ('City of Riverside', '3900 Main Street', 'Riverside', '92522', 'City Clerk'),
    'Rocklin': ('City of Rocklin', '3970 Rocklin Road', 'Rocklin', '95677', 'City Clerk'),
    'Rohnert Park': ('City of Rohnert Park', '130 Avram Avenue', 'Rohnert Park', '94928', 'City Clerk'),
    'Rolling Hills': ('City of Rolling Hills', '2 Portuguese Bend Road', 'Rolling Hills', '90274', 'City Clerk'),
    'Rolling Hills Estates': ('City of Rolling Hills Estates', '4045 Palos Verdes Drive North', 'Rolling Hills Estates', '90274', 'City Clerk'),
    'Rosemead': ('City of Rosemead', '8838 East Valley Boulevard', 'Rosemead', '91770', 'City Clerk'),
    'Roseville': ('City of Roseville', '311 Vernon Street', 'Roseville', '95678', 'City Clerk'),
    'Ross': ('Town of Ross', '31 Sir Francis Drake Boulevard', 'Ross', '94957', 'Town Clerk'),
    'Sacramento': ('City of Sacramento', '915 I Street', 'Sacramento', '95814', 'City Clerk'),
    'Salinas': ('City of Salinas', '200 Lincoln Avenue', 'Salinas', '93901', 'City Clerk'),
    'San Anselmo': ('Town of San Anselmo', '525 San Anselmo Avenue', 'San Anselmo', '94960', 'Town Clerk'),
    'San Bernardino': ('City of San Bernardino', '290 North D Street', 'San Bernardino', '92401', 'City Clerk'),
    'San Bruno': ('City of San Bruno', '567 El Camino Real', 'San Bruno', '94066', 'City Clerk'),
    'San Carlos': ('City of San Carlos', '600 Elm Street', 'San Carlos', '94070', 'City Clerk'),
    'San Clemente': ('City of San Clemente', '910 Calle Negocio', 'San Clemente', '92673', 'City Clerk'),
    'San Diego': ('City of San Diego', '202 C Street', 'San Diego', '92101', 'City Clerk'),
    'San Dimas': ('City of San Dimas', '245 East Bonita Avenue', 'San Dimas', '91773', 'City Clerk'),
    'San Fernando': ('City of San Fernando', '117 Macneil Street', 'San Fernando', '91340', 'City Clerk'),
    'San Francisco': ('City of San Francisco', '1 Dr Carlton B Goodlett Place', 'San Francisco', '94102', 'City Clerk'),
    'San Gabriel': ('City of San Gabriel', '425 South Mission Drive', 'San Gabriel', '91776', 'City Clerk'),
    'San Jacinto': ('City of San Jacinto', '595 South San Jacinto Avenue', 'San Jacinto', '92583', 'City Clerk'),
    'San Joaquin': ('City of San Joaquin', '21900 Highway 33', 'San Joaquin', '93660', 'City Clerk'),
    'San Jose': ('City of San Jose', '200 East Santa Clara Street', 'San Jose', '95113', 'City Clerk'),
    'San Juan Bautista': ('City of San Juan Bautista', '311 Second Street', 'San Juan Bautista', '95045', 'City Clerk'),
    'San Juan Capistrano': ('City of San Juan Capistrano', '32400 Paseo Adelanto', 'San Juan Capistrano', '92675', 'City Clerk'),
    'San Leandro': ('City of San Leandro', '835 East 14th Street', 'San Leandro', '94577', 'City Clerk'),
    'San Luis Obispo': ('City of San Luis Obispo', '990 Palm Street', 'San Luis Obispo', '93401', 'City Clerk'),
    'San Marcos': ('City of San Marcos', '1 Civic Center Drive', 'San Marcos', '92069', 'City Clerk'),
    'San Marino': ('City of San Marino', '2200 Huntington Drive', 'San Marino', '91108', 'City Clerk'),
    'San Mateo': ('City of San Mateo', '330 West 20th Avenue', 'San Mateo', '94403', 'City Clerk'),
    'San Pablo': ('City of San Pablo', '13831 San Pablo Avenue', 'San Pablo', '94806', 'City Clerk'),
    'San Rafael': ('City of San Rafael', '1400 Fifth Avenue', 'San Rafael', '94901', 'City Clerk'),
    'San Ramon': ('City of San Ramon', '7000 Bollinger Canyon Road', 'San Ramon', '94583', 'City Clerk'),
    'Sand City': ('City of Sand City', '1 Pendergrass Way', 'Sand City', '93955', 'City Clerk'),
    'Sanger': ('City of Sanger', '1700 7th Street', 'Sanger', '93657', 'City Clerk'),
    'Santa Ana': ('City of Santa Ana', '20 Civic Center Plaza', 'Santa Ana', '92701', 'City Clerk'),
    'Santa Barbara': ('City of Santa Barbara', '735 Anacapa Street', 'Santa Barbara', '93101', 'City Clerk'),
    'Santa Clara': ('City of Santa Clara', '1500 Warburton Avenue', 'Santa Clara', '95050', 'City Clerk'),
    'Santa Clarita': ('City of Santa Clarita', '23920 Valencia Boulevard', 'Santa Clarita', '91355', 'City Clerk'),
    'Santa Cruz': ('City of Santa Cruz', '809 Center Street', 'Santa Cruz', '95060', 'City Clerk'),
    'Santa Fe Springs': ('City of Santa Fe Springs', '11710 Telegraph Road', 'Santa Fe Springs', '90670', 'City Clerk'),
    'Santa Maria': ('City of Santa Maria', '110 East Cook Street', 'Santa Maria', '93454', 'City Clerk'),
    'Santa Monica': ('City of Santa Monica', '1685 Main Street', 'Santa Monica', '90401', 'City Clerk'),
    'Santa Paula': ('City of Santa Paula', '970 Ventura Street', 'Santa Paula', '93060', 'City Clerk'),
    'Santa Rosa': ('City of Santa Rosa', '100 Santa Rosa Avenue', 'Santa Rosa', '95404', 'City Clerk'),
    'Santee': ('City of Santee', '10601 Magnolia Avenue', 'Santee', '92071', 'City Clerk'),
    'Saratoga': ('City of Saratoga', '13777 Fruitvale Avenue', 'Saratoga', '95070', 'City Clerk'),
    'Sausalito': ('City of Sausalito', '420 Litho Street', 'Sausalito', '94965', 'City Clerk'),
    'Scotts Valley': ('City of Scotts Valley', '1 Civic Center Drive', 'Scotts Valley', '95066', 'City Clerk'),
    'Seal Beach': ('City of Seal Beach', '211 Eighth Street', 'Seal Beach', '90740', 'City Clerk'),
    'Seaside': ('City of Seaside', '440 Harcourt Avenue', 'Seaside', '93955', 'City Clerk'),
    'Sebastopol': ('City of Sebastopol', '7120 Bodega Avenue', 'Sebastopol', '95472', 'City Clerk'),
    'Selma': ('City of Selma', '1710 Tucker Street', 'Selma', '93662', 'City Clerk'),
    'Shafter': ('City of Shafter', '336 Pacific Avenue', 'Shafter', '93263', 'City Clerk'),
    'Shasta Lake': ('City of Shasta Lake', '1650 Stanton Drive', 'Shasta Lake', '96019', 'City Clerk'),
    'Sierra Madre': ('City of Sierra Madre', '232 West Sierra Madre Boulevard', 'Sierra Madre', '91024', 'City Clerk'),
    'Signal Hill': ('City of Signal Hill', '2175 Cherry Avenue', 'Signal Hill', '90755', 'City Clerk'),
    'Simi Valley': ('City of Simi Valley', '2929 Tapo Canyon Road', 'Simi Valley', '93063', 'City Clerk'),
    'Solana Beach': ('City of Solana Beach', '635 South Highway 101', 'Solana Beach', '92075', 'City Clerk'),
    'Soledad': ('City of Soledad', '248 Main Street', 'Soledad', '93960', 'City Clerk'),
    'Solvang': ('City of Solvang', '1644 Oak Street', 'Solvang', '93463', 'City Clerk'),
    'Sonoma': ('City of Sonoma', 'No. 1 The Plaza', 'Sonoma', '95476', 'City Clerk'),
    'Sonora': ('City of Sonora', '94 North Washington Street', 'Sonora', '95370', 'City Clerk'),
    'South El Monte': ('City of South El Monte', '1415 Santa Anita Avenue', 'South El Monte', '91733', 'City Clerk'),
    'South Gate': ('City of South Gate', '8650 California Avenue', 'South Gate', '90280', 'City Clerk'),
    'South Lake Tahoe': ('City of South Lake Tahoe', '1901 Airport Road', 'South Lake Tahoe', '96150', 'City Clerk'),
    'South Pasadena': ('City of South Pasadena', '1414 Mission Street', 'South Pasadena', '91030', 'City Clerk'),
    'South San Francisco': ('City of South San Francisco', '400 Grand Avenue', 'South San Francisco', '94080', 'City Clerk'),
    'St. Helena': ('City of St. Helena', '1480 Main Street', 'St. Helena', '94574', 'City Clerk'),
    'Stanton': ('City of Stanton', '7800 Katella Avenue', 'Stanton', '90680', 'City Clerk'),
    'Stockton': ('City of Stockton', '425 North El Dorado Street', 'Stockton', '95202', 'City Clerk'),
    'Suisun City': ('City of Suisun City', '701 Civic Center Boulevard', 'Suisun City', '94585', 'City Clerk'),
    'Sunnyvale': ('City of Sunnyvale', '456 West Olive Avenue', 'Sunnyvale', '94086', 'City Clerk'),
    'Susanville': ('City of Susanville', '66 North Lassen Street', 'Susanville', '96130', 'City Clerk'),
    'Sutter Creek': ('City of Sutter Creek', '18 Main Street', 'Sutter Creek', '95685', 'City Clerk'),
    'Taft': ('City of Taft', '209 East Kern Street', 'Taft', '93268', 'City Clerk'),
    'Tehachapi': ('City of Tehachapi', '115 South Robinson Street', 'Tehachapi', '93561', 'City Clerk'),
    'Tehama': ('City of Tehama', '250 Cavalier Drive', 'Tehama', '96090', 'City Clerk'),
    'Temecula': ('City of Temecula', '41000 Main Street', 'Temecula', '92590', 'City Clerk'),
    'Temple City': ('City of Temple City', '9701 Las Tunas Drive', 'Temple City', '91780', 'City Clerk'),
    'Thousand Oaks': ('City of Thousand Oaks', '2100 Thousand Oaks Boulevard', 'Thousand Oaks', '91362', 'City Clerk'),
    'Tiburon': ('Town of Tiburon', '1505 Tiburon Boulevard', 'Tiburon', '94920', 'Town Clerk'),
    'Torrance': ('City of Torrance', '3031 Torrance Boulevard', 'Torrance', '90503', 'City Clerk'),
    'Tracy': ('City of Tracy', '333 Civic Center Plaza', 'Tracy', '95376', 'City Clerk'),
    'Trinidad': ('City of Trinidad', '409 Trinity Street', 'Trinidad', '95570', 'City Clerk'),
    'Truckee': ('Town of Truckee', '10183 Truckee Airport Road', 'Truckee', '96161', 'Town Clerk'),
    'Tulare': ('City of Tulare', '411 East Kern Avenue', 'Tulare', '93274', 'City Clerk'),
    'Tulelake': ('City of Tulelake', '591 Main Street', 'Tulelake', '96134', 'City Clerk'),
    'Turlock': ('City of Turlock', '156 South Broadway', 'Turlock', '95380', 'City Clerk'),
    'Tustin': ('City of Tustin', '300 Centennial Way', 'Tustin', '92780', 'City Clerk'),
    'Twentynine Palms': ('City of Twentynine Palms', '6136 Adobe Road', 'Twentynine Palms', '92277', 'City Clerk'),
    'Ukiah': ('City of Ukiah', '300 Seminary Avenue', 'Ukiah', '95482', 'City Clerk'),
    'Union City': ('City of Union City', '34009 Alvarado-Niles Road', 'Union City', '94587', 'City Clerk'),
    'Upland': ('City of Upland', '460 North Euclid Avenue', 'Upland', '91786', 'City Clerk'),
    'Vacaville': ('City of Vacaville', '650 Merchant Street', 'Vacaville', '95688', 'City Clerk'),
    'Vallejo': ('City of Vallejo', '555 Santa Clara Street', 'Vallejo', '94590', 'City Clerk'),
    'Ventura': ('City of Ventura', '501 Poli Street', 'Ventura', '93001', 'City Clerk'),
    'Vernon': ('City of Vernon', '4305 South Santa Fe Avenue', 'Vernon', '90058', 'City Clerk'),
    'Victorville': ('City of Victorville', '14343 Civic Drive', 'Victorville', '92392', 'City Clerk'),
    'Villa Park': ('City of Villa Park', '17855 Santiago Boulevard', 'Villa Park', '92861', 'City Clerk'),
    'Visalia': ('City of Visalia', '707 West Acequia Avenue', 'Visalia', '93291', 'City Clerk'),
    'Vista': ('City of Vista', '200 Civic Center Drive', 'Vista', '92084', 'City Clerk'),
    'Walnut': ('City of Walnut', '21201 La Puente Road', 'Walnut', '91789', 'City Clerk'),
    'Walnut Creek': ('City of Walnut Creek', '1666 North Main Street', 'Walnut Creek', '94596', 'City Clerk'),
    'Wasco': ('City of Wasco', '746 8th Street', 'Wasco', '93280', 'City Clerk'),
    'Waterford': ('City of Waterford', '101 East Street', 'Waterford', '95386', 'City Clerk'),
    'Watsonville': ('City of Watsonville', '275 Main Street', 'Watsonville', '95076', 'City Clerk'),
    'Weed': ('City of Weed', '550 Main Street', 'Weed', '96094', 'City Clerk'),
    'West Covina': ('City of West Covina', '1444 West Garvey Avenue North', 'West Covina', '91790', 'City Clerk'),
    'West Hollywood': ('City of West Hollywood', '8300 Santa Monica Boulevard', 'West Hollywood', '90069', 'City Clerk'),
    'West Sacramento': ('City of West Sacramento', '1110 West Capitol Avenue', 'West Sacramento', '95691', 'City Clerk'),
    'Westlake Village': ('City of Westlake Village', '31200 Oak Crest Drive', 'Westlake Village', '91361', 'City Clerk'),
    'Westminster': ('City of Westminster', '8200 Westminster Boulevard', 'Westminster', '92683', 'City Clerk'),
    'Westmorland': ('City of Westmorland', '355 South Center Street', 'Westmorland', '92281', 'City Clerk'),
    'Wheatland': ('City of Wheatland', '111 C Street', 'Wheatland', '95692', 'City Clerk'),
    'Whittier': ('City of Whittier', '13230 Penn Street', 'Whittier', '90602', 'City Clerk'),
    'Wildomar': ('City of Wildomar', '23873 Clinton Keith Road', 'Wildomar', '92595', 'City Clerk'),
    'Williams': ('City of Williams', '810 E Street', 'Williams', '95987', 'City Clerk'),
    'Willits': ('City of Willits', '111 East Commercial Street', 'Willits', '95490', 'City Clerk'),
    'Willows': ('City of Willows', '201 North Lassen Street', 'Willows', '95988', 'City Clerk'),
    'Windsor': ('Town of Windsor', '9291 Old Redwood Highway', 'Windsor', '95492', 'Town Clerk'),
    'Winters': ('City of Winters', '318 First Street', 'Winters', '95694', 'City Clerk'),
    'Woodlake': ('City of Woodlake', '350 West Whitney Avenue', 'Woodlake', '93286', 'City Clerk'),
    'Woodland': ('City of Woodland', '300 First Street', 'Woodland', '95695', 'City Clerk'),
    'Woodside': ('Town of Woodside', '2955 Woodside Road', 'Woodside', '94062', 'Town Clerk'),
    'Yorba Linda': ('City of Yorba Linda', '4845 Casa Loma Avenue', 'Yorba Linda', '92886', 'City Clerk'),
    'Yountville': ('Town of Yountville', '6550 Yount Street', 'Yountville', '94599', 'Town Clerk'),
    'Yreka': ('City of Yreka', '701 Fourth Street', 'Yreka', '96097', 'City Clerk'),
    'Yuba City': ('City of Yuba City', '1201 Civic Center Boulevard', 'Yuba City', '95993', 'City Clerk'),
    'Yucaipa': ('City of Yucaipa', '34272 Yucaipa Boulevard', 'Yucaipa', '92399', 'City Clerk'),
    'Yucca Valley': ('Town of Yucca Valley', '57090 29 Palms Highway', 'Yucca Valley', '92284', 'Town Clerk'),
}


def _build() -> dict:
    out = {}
    for key, (name, address, city, zip_, clerk) in _DATA.items():
        out[key] = {
            "name":          name,
            "address":       address,
            "city":          city,
            "state":         "CA",
            "zip":           zip_,
            "agent_name":    clerk,
            "agent_title":   clerk,
            "agent_address": address,
            "agent_city":    city,
            "agent_state":   "CA",
            "agent_zip":     zip_,
        }
    return out


CA_MUNICIPALITIES: dict[str, dict] = _build()

ALL_CITIES: list[str] = sorted(CA_MUNICIPALITIES.keys())


def defendant_info(city: str) -> dict:
    """Return defendant dict for a given city. Falls back to a blank template."""
    if city in CA_MUNICIPALITIES:
        return CA_MUNICIPALITIES[city].copy()
    return {
        "name":          f"City of {city}",
        "address":       "City Hall",
        "city":          city,
        "state":         "CA",
        "zip":           "",
        "agent_name":    "City Clerk",
        "agent_title":   "City Clerk",
        "agent_address": "City Hall",
        "agent_city":    city,
        "agent_state":   "CA",
        "agent_zip":     "",
    }
